#include "../sr_pch.h"
#pragma data_seg(".pcode")
#pragma const_seg(".pcode")

#define PCL0_COUNT                194
#define PCL1_COUNT                225
#define PCL2_COUNT                240
#define PCL3_COUNT                197
#define PCL4_COUNT                240

const char      * pcit_ive = "InvalidExcode\0";
const char      * pcit_unk = "Unknown\0";

/*P-Code 单字节指令集 (标准指令集)*/
const VB_PCODE_STD_INST PCodeStdInst[251] =
{
  /*00h*/{ "LargeBos", NULL, 0, 2 },
  /*01h*/{ "InvalidExcode", NULL, 0, 1 },
  /*02h*/{ "LargeBos", NULL, 0, 2 },
  /*03h*/{ "InvalidExcode", NULL, 0, 1 },
  /*04h*/{ "FLdRfVar", _T(" %a"), PCT_RETONEVAR, 3 },
  /*05h*/{ "ImpAdLdRf", _T(" %c"), PCT_STD, 3 },
  /*06h*/{ "MemLdRfVar", NULL, 0, 3 },
  /*07h*/{ "FMemLdRf", NULL, 0, 5 },
  /*08h*/{ "FLdPr", _T(" = SR,%a"), PCT_STD, 3 },
  /*09h*/{ "ImpAdCallHresult", _T(" ::call %c(%a)"), PCT_STD, 5 },
  /*0Ah*/{ "ImpAdCallFPR4", _T(" %x"), PCT_STD, 5 },
  /*0Bh*/{ "ImpAdCallI2", _T(" ::call %c(%a)"), PCT_STD, 5 },
  /*0Ch*/{ "ImpAdCallCy", _T(" ::call %c(%a)"), PCT_STD, 5 },
  /*0Dh*/{ "VCallHresult", _T(" %v"), PCT_STD, 5 },
  /*0Eh*/{ "VCallFPR8", NULL, 0, 3 },
  /*0Fh*/{ "VCallAd", NULL, PCT_STD, 3 },
  /*10h*/{ "ThisVCallHresult", _T(" %2 %c"), PCT_STD, 5 },
  /*11h*/{ "ThisVCall", NULL, 0, 3 },
  /*12h*/{ "ThisVCallAd", NULL, 0, 3 },
  /*13h*/{ "ExitProcHresult", NULL, PCF_ENDPROC | PCT_STD, 1 },
  /*14h*/{ "ExitProc", NULL, PCF_ENDPROC | PCT_STD, 1 },
  /*15h*/{ "ExitProcI2", NULL, PCT_NONE, 1 },
  /*16h*/{ "ExitProcR4", NULL, PCT_NONE, 1 },
  /*17h*/{ "ExitProcR8", NULL, PCT_NONE, 1 },
  /*18h*/{ "ExitProcCy", NULL, PCT_NONE, 1 },
  /*19h*/{ "FStAdFunc", NULL, 0, 3 },
  /*1Ah*/{ "FFree1Ad", NULL, 0, 3 },
  /*1Bh*/{ "LitStr", _T(" %s"), PCT_STD, 3 },
  /*1Ch*/{ "BranchF", _T(" %l"), PCT_STD, 3 },
  /*1Dh*/{ "BranchT", _T(" %l"), PCT_STD, 3 },
  /*1Eh*/{ "Branch", _T(" %l"), PCT_STD, 3 },
  /*1Fh*/{ "CRec2Ansi", _T(" %2"), PCT_STD, 3 },
  /*20h*/{ "CRec2Uni", NULL, 0, 3 },
  /*21h*/{ "FLdPrThis", NULL, PCT_NONE, 1 },
  /*22h*/{ "ImpAdLdPr", _T(" [%c]"), PCT_STD, 3 },
  /*23h*/{ "FStStrNoPop", NULL, 0, 3 },
  /*24h*/{ "NewIfNullPr", _T(" %t"), PCT_IDX, 3 },
  /*25h*/{ "PopAdLdVar", NULL, PCT_NONE, 1 },
  /*26h*/{ "AryDescTemp", NULL, 0, 3 },
  /*27h*/{ "LitVar_Missing", NULL, PCT_STD, 3 },
  /*28h*/{ "LitVarI2", _T(" %a,%2"), PCT_STD, 5 },
  /*29h*/{ "FFreeAd", NULL, PCT_CLEARMEMORY, -1 },
  /*2Ah*/{ "ConcatStr", NULL, PCT_NONE, 1 },
  /*2Bh*/{ "PopTmpLdAd2", NULL, 0, 3 },
  /*2Ch*/{ "LateIdSt", NULL, 0, 5 },
  /*2Dh*/{ "AryUnlock", NULL, 0, 3 },
  /*2Eh*/{ "AryLock", NULL, 0, 3 },
  /*2Fh*/{ "FFree1Str", NULL, PCT_ONESTRING, 3 },
  /*30h*/{ "PopTmpLdAd8", NULL, 0, 3 },
  /*31h*/{ "FStStr", NULL, 0, 3 },
  /*32h*/{ "FFreeStr", NULL, PCT_CLEARMEMORY, -1 },
  /*33h*/{ "LdFixedStr", _T(" %s"), PCT_STD, 3 },
  /*34h*/{ "CStr2Ansi", NULL, PCT_NONE, 1 },
  /*35h*/{ "FFree1Var", NULL, 0, 3 },
  /*36h*/{ "FFreeVar", NULL, PCT_CLEARMEMORY, -1 },
  /*37h*/{ "PopFPR4", NULL, PCT_IDX, 1 },
  /*38h*/{ "CopyBytes", NULL, 0, 3 },
  /*39h*/{ "PopFPR8", NULL, PCT_NONE, 1 },
  /*3Ah*/{ "LitVarStr", _T(" %a %s"), PCT_STD, 5 },
  /*3Bh*/{ "Ary1StStrCopy", NULL, PCT_NONE, 1 },
  /*3Ch*/{ "GetLastError", NULL, PCT_NONE, 1 },
  /*3Dh*/{ "CastAd", NULL, 0, 3 },
  /*3Eh*/{ "FLdZeroAd", NULL, 0, 3 },
  /*3Fh*/{ "CVarCy", NULL, 0, 3 },
  /*40h*/{ "Ary1LdRf", NULL, PCT_NONE, 1 },
  /*41h*/{ "Ary1LdPr", NULL, PCT_NONE, 1 },
  /*42h*/{ "CR4Var", NULL, PCT_NONE, 1 },
  /*43h*/{ "FStStrCopy", _T(" %a"), PCT_STD, 3 },
  /*44h*/{ "CVarI2", NULL, 0, 3 },
  /*45h*/{ "Error", NULL, PCT_NONE, 1 },
  /*46h*/{ "CVarStr", NULL, 0, 3 },
  /*47h*/{ "StFixedStr", _T(" %l %a"), PCT_STD, 3 },
  /*48h*/{ "ILdPr", NULL, 0, 3 },
  /*49h*/{ "PopAdLd4", NULL, PCT_NONE, 1 },
  /*4Ah*/{ "FnLenStr", NULL, PCT_NONE, 1 },
  /*4Bh*/{ "OnErrorGoto", _T(" %l"), PCT_STD, 3 },
  /*4Ch*/{ "FnLBound", NULL, PCT_NONE, 1 },
  /*4Dh*/{ "CVarRef", NULL, 0, 5 },
  /*4Eh*/{ "FStVarCopyObj", NULL, 0, 3 },
  /*4Fh*/{ "MidStr", NULL, 0, 3 },
  /*50h*/{ "CI4Str", NULL, PCT_NONE, 1 },
  /*51h*/{ "FLdZeroAd", NULL, 0, 3 },
  /*52h*/{ "Ary1StVar", NULL, PCT_NONE, 1 },
  /*53h*/{ "CBoolCy", NULL, PCT_NONE, 1 },
  /*54h*/{ "FMemStStrCopy", NULL, 0, 5 },
  /*55h*/{ "CI2Var", NULL, PCT_NONE, 1 },
  /*56h*/{ "NewIfNullAd", NULL, 0, 3 },
  /*57h*/{ "LateMemLdVar", NULL, 0, 5 },
  /*58h*/{ "MemLdPr", NULL, 0, 3 },
  /*59h*/{ "PopTmpLdAdStr", NULL, 0, 3 },
  /*5Ah*/{ "Erase", NULL, PCT_NONE, 1 },
  /*5Bh*/{ "FStAdFuncNoPop", NULL, 0, 3 },
  /*5Ch*/{ "BranchFVar", NULL, 0, 3 },
  /*5Dh*/{ "HardType", NULL, PCT_NONE, 1 },
  /*5Eh*/{ "ImpAdCallI4", _T("  %x"), PCT_STD, 5 },
  /*5Fh*/{ "FMemLdPr", NULL, 0, 5 },
  /*60h*/{ "CStrVarTmp", NULL, PCT_NONE, 1 },
  /*61h*/{ "LateIdLdVar", NULL, 0, 7 },
  /*62h*/{ "IStDarg", NULL, 0, 3 },
  /*63h*/{ "LitVar_TRUE", NULL, 0, 3 },
  /*64h*/{ "NextI2", NULL, 0, 5 },
  /*65h*/{ "NextStepI2", NULL, 0, 5 },
  /*66h*/{ "NextI4", NULL, 0, 5 },
  /*67h*/{ "NextStepI4", NULL, 0, 5 },
  /*68h*/{ "NextStepR4", NULL, 0, 5 },
  /*69h*/{ "NextStepR8", NULL, 0, 5 },
  /*6Ah*/{ "NextStepCy", NULL, 0, 5 },
  /*6Bh*/{ "FLdI2", _T(" [%a]"), PCT_STD, 3 },
  /*6Ch*/{ "ILdRf", _T(" [%a]"), PCT_STD, 3 },
  /*6Dh*/{ "FLdR8", NULL, 0, 3 },
  /*6Eh*/{ "FLdFPR4", NULL, 0, 3 },
  /*6Fh*/{ "FLdFPR8", NULL, 0, 3 },
  /*70h*/{ "FStI2", _T(" [%a]"), PCT_STD, 3 },
  /*71h*/{ "FStR4", _T(" [%a]"), PCT_STD, 3 },
  /*72h*/{ "FStR8", NULL, 0, 3 },
  /*73h*/{ "FStFPR4", NULL, 0, 3 },
  /*74h*/{ "FStFPR8", NULL, 0, 3 },
  /*75h*/{ "ImpAdLdI2", NULL, 0, 3 },
  /*76h*/{ "ImpAdLdI4", _T(" [%c]"), PCT_STD, 3 },
  /*77h*/{ "ImpAdLdCy", _T(" %c"), PCT_STD, 3 },
  /*78h*/{ "ImpAdLdFPR4", _T(" %c"), PCT_STD, 3 },
  /*79h*/{ "ImpAdLdFPR8", _T(" %c"), PCT_STD, 3 },
  /*7Ah*/{ "ImpAdStI2", _T(" %c"), PCT_STD, 3 },
  /*7Bh*/{ "ImpAdStR4", _T(" %c"), PCT_STD, 3 },
  /*7Ch*/{ "ImpAdStCy", _T(" %c"), PCT_STD, 3 },
  /*7Dh*/{ "ImpAdStFPR4", _T(" %c"), PCT_STD, 3 },
  /*7Eh*/{ "ImpAdStFPR8", _T(" %c"), PCT_STD, 3 },
  /*7Fh*/{ "ILdI2", _T(" %a"), PCT_STD, 3 },
  /*80h*/{ "ILdI4", _T(" %a"), PCT_STD, 3 },
  /*81h*/{ "ILdR8", _T(" %a"), PCT_STD, 3 },
  /*82h*/{ "ILdFPR4", _T(" %a"), PCT_STD, 3 },
  /*83h*/{ "ILdFPR8", _T(" %a"), PCT_STD, 3 },
  /*84h*/{ "IStI2", _T(" %c"), PCT_STD, 3 },
  /*85h*/{ "IStI4", _T(" %c"), PCT_STD, 3 },
  /*86h*/{ "IStR8", NULL, 0, 3 },
  /*87h*/{ "IStFPR4", NULL, 0, 3 },
  /*88h*/{ "IStFPR8", NULL, 0, 3 },
  /*89h*/{ "MemLdI2", _T(" [%2+SR]"), PCT_IDX, 3 },
  /*8Ah*/{ "MemLdStr", NULL, 0, 3 },
  /*8Bh*/{ "MemLdR8", NULL, 0, 3 },
  /*8Ch*/{ "MemLdFPR4", NULL, 0, 3 },
  /*8Dh*/{ "MemLdFPR8", NULL, 0, 3 },
  /*8Eh*/{ "MemStI2", NULL, 0, 3 },
  /*8Fh*/{ "MemStI4", NULL, 0, 3 },
  /*90h*/{ "MemStR8", NULL, 0, 3 },
  /*91h*/{ "MemStFPR4", NULL, 0, 3 },
  /*92h*/{ "MemStFPR8", NULL, 0, 3 },
  /*93h*/{ "FMemLdI2", NULL, 0, 5 },
  /*94h*/{ "FMemLdR4", NULL, 0, 5 },
  /*95h*/{ "FMemLdCy", NULL, 0, 5 },
  /*96h*/{ "FMemLdFPR4", NULL, 0, 5 },
  /*97h*/{ "FMemLdFPR8", NULL, 0, 5 },
  /*98h*/{ "FMemStI2", _T(" [[%a]+%2]"), PCT_STD, 5 },
  /*99h*/{ "FMemStI4", _T(" [[%a]+%2]"), PCT_STD, 5 },
  /*9Ah*/{ "FMemStR8", _T(" [[%a]+%2]"), PCT_STD, 5 },
  /*9Bh*/{ "FMemStFPR4", _T(" [[%a]+%2]"), PCT_STD, 5 },
  /*9Ch*/{ "FMemStFPR8", _T(" [[%a]+%2]"), PCT_STD, 5 },
  /*9Dh*/{ "Ary1LdI2", NULL, PCT_NONE, 1 },
  /*9Eh*/{ "Ary1LdI4", NULL, PCT_NONE, 1 },
  /*9Fh*/{ "Ary1LdCy", NULL, PCT_NONE, 1 },
  /*A0h*/{ "Ary1LdFPR4", NULL, PCT_NONE, 1 },
  /*A1h*/{ "Ary1LdFPR8", NULL, PCT_NONE, 1 },
  /*A2h*/{ "Ary1StI2", NULL, PCT_NONE, 1 },
  /*A3h*/{ "Ary1StI4", NULL, PCT_NONE, 1 },
  /*A4h*/{ "Ary1StCy", NULL, PCT_NONE, 1 },
  /*A5h*/{ "Ary1StFPR4", NULL, PCT_NONE, 1 },
  /*A6h*/{ "Ary1StFPR8", NULL, PCT_NONE, 1 },
  /*A7h*/{ "AryLdPr", NULL, 0, 3 },
  /*A8h*/{ "AryLdRf", NULL, 0, 3 },
  /*A9h*/{ "AddI2", NULL, PCT_NONE, 1 },
  /*AAh*/{ "AddI4", NULL, PCT_NONE, 1 },
  /*ABh*/{ "AddR8", NULL, PCT_NONE, 1 },
  /*ACh*/{ "AddCy", NULL, PCT_NONE, 1 },
  /*ADh*/{ "SubI2", NULL, PCT_NONE, 1 },
  /*AEh*/{ "SubI4", NULL, PCT_NONE, 1 },
  /*AFh*/{ "SubR4", NULL, PCT_NONE, 1 },
  /*B0h*/{ "SubCy", NULL, PCT_NONE, 1 },
  /*B1h*/{ "MulI2", NULL, PCT_NONE, 1 },
  /*B2h*/{ "MulI4", NULL, PCT_NONE, 1 },
  /*B3h*/{ "MulR8", NULL, PCT_NONE, 1 },
  /*B4h*/{ "MulCy", NULL, PCT_NONE, 1 },
  /*B5h*/{ "MulCyI2", NULL, PCT_NONE, 1 },
  /*B6h*/{ "DivR8", NULL, PCT_NONE, 1 },
  /*B7h*/{ "UMiI2", NULL, PCT_NONE, 1 },
  /*B8h*/{ "UMiI4", NULL, PCT_NONE, 1 },
  /*B9h*/{ "UMiR8", NULL, PCT_NONE, 1 },
  /*BAh*/{ "UMiCy", NULL, PCT_NONE, 1 },
  /*BBh*/{ "FnAbsI2", NULL, PCT_NONE, 1 },
  /*BCh*/{ "FnAbsI4", NULL, PCT_NONE, 1 },
  /*BDh*/{ "FnAbsR4", NULL, PCT_NONE, 1 },
  /*BEh*/{ "FnAbsCy", NULL, PCT_NONE, 1 },
  /*BFh*/{ "IDvI2", NULL, PCT_NONE, 1 },
  /*C0h*/{ "IDvI4", NULL, PCT_NONE, 1 },
  /*C1h*/{ "ModI2", NULL, PCT_NONE, 1 },
  /*C2h*/{ "ModI4", NULL, PCT_NONE, 1 },
  /*C3h*/{ "NotI4", NULL, PCT_NONE, 1 },
  /*C4h*/{ "AndI4", NULL, PCT_NONE, 1 },
  /*C5h*/{ "OrI4", NULL, PCT_NONE, 1 },
  /*C6h*/{ "EqI2", NULL, PCT_NONE, 1 },
  /*C7h*/{ "EqI4", NULL, PCT_NONE, 1 },
  /*C8h*/{ "EqR4", NULL, PCT_NONE, 1 },
  /*C9h*/{ "EqCy", NULL, PCT_NONE, 1 },
  /*CAh*/{ "EqCyR8", NULL, PCT_NONE, 1 },
  /*CBh*/{ "NeI2", NULL, PCT_NONE, 1 },
  /*CCh*/{ "NeI4", NULL, PCT_NONE, 1 },
  /*CDh*/{ "NeR8", NULL, PCT_NONE, 1 },
  /*CEh*/{ "NeCy", NULL, PCT_NONE, 1 },
  /*CFh*/{ "NeCyR8", NULL, PCT_NONE, 1 },
  /*D0h*/{ "LtI2", NULL, PCT_NONE, 1 },
  /*D1h*/{ "LtI4", NULL, PCT_NONE, 1 },
  /*D2h*/{ "LtR8", NULL, PCT_NONE, 1 },
  /*D3h*/{ "LtCy", NULL, PCT_NONE, 1 },
  /*D4h*/{ "LtCyR8", NULL, PCT_NONE, 1 },
  /*D5h*/{ "LeI2", NULL, PCT_NONE, 1 },
  /*D6h*/{ "LeI4", NULL, PCT_NONE, 1 },
  /*D7h*/{ "LeR8", NULL, PCT_NONE, 1 },
  /*D8h*/{ "LeCy", NULL, PCT_NONE, 1 },
  /*D9h*/{ "LeCyR8", NULL, PCT_NONE, 1 },
  /*DAh*/{ "GtI2", NULL, PCT_NONE, 1 },
  /*DBh*/{ "GtI4", NULL, PCT_NONE, 1 },
  /*DCh*/{ "GtR4", NULL, PCT_NONE, 1 },
  /*DDh*/{ "GtCy", NULL, PCT_NONE, 1 },
  /*DEh*/{ "GtCyR8", NULL, PCT_NONE, 1 },
  /*DFh*/{ "GeI2", NULL, PCT_NONE, 1 },
  /*E0h*/{ "GeI4", NULL, PCT_NONE, 1 },
  /*E1h*/{ "GeR8", NULL, PCT_NONE, 1 },
  /*E2h*/{ "GeCy", NULL, PCT_NONE, 1 },
  /*E3h*/{ "GeCyR8", NULL, PCT_NONE, 1 },
  /*E4h*/{ "CI2I4", NULL, PCT_NONE, 1 },
  /*E5h*/{ "CI2R8", NULL, PCT_NONE, 1 },
  /*E6h*/{ "CI2Cy", NULL, PCT_NONE, 1 },
  /*E7h*/{ "CI4UI1", NULL, PCT_NONE, 1 },
  /*E8h*/{ "CI4R8", NULL, PCT_NONE, 1 },
  /*E9h*/{ "CI4Cy", NULL, PCT_NONE, 1 },
  /*EAh*/{ "CR4R4", NULL, PCT_NONE, 1 },
  /*EBh*/{ "CR8I2", NULL, PCT_NONE, 1 },
  /*ECh*/{ "CR8I4", NULL, PCT_NONE, 1 },
  /*EDh*/{ "CR8R8", NULL, PCT_NONE, 1 },
  /*EEh*/{ "CR8Cy", NULL, PCT_NONE, 1 },
  /*EFh*/{ "CCyI2", NULL, PCT_NONE, 1 },
  /*F0h*/{ "CCyI4", NULL, PCT_NONE, 1 },
  /*F1h*/{ "CCyR4", NULL, PCT_NONE, 1 },
  /*F2h*/{ "CDateR8", NULL, PCT_NONE, 1 },
  /*F3h*/{ "LitI2", _T(" %2"), PCT_STD, 3 },
  /*F4h*/{ "LitI2_Byte", _T(" %1"), PCT_STD, 2 },
  /*F5h*/{ "LitI4", _T(" %4"), PCT_STD, 5 },
  /*F6h*/{ "LitCy", NULL, 0, 9 },
  /*F7h*/{ "LitCy4", NULL, 0, 5 },
  /*F8h*/{ "LitI2FP", NULL, 0, 3 },
  /*F9h*/{ "LitR4FP", NULL, 0, 5 },
  /*FAh*/{ "LitDate", NULL, 0, 9 }
};

/*P-Code 双字节指令集0 (扩展指令集) 0xFB前缀*/
const VB_PCODE_LEAD_INST PCodeLead0Inst[256] =
{
  /*00h*/{ pcit_ive, 0, 1 },
  /*01h*/{ "ImpUI1", PCT_NONE, 1 },
  /*02h*/{ "ImpI4", PCT_NONE, 1 },
  /*03h*/{ "ImpI4", PCT_NONE, 1 },
  /*04h*/{ pcit_ive, 0, 1 },
  /*05h*/{ pcit_ive, 0, 1 },
  /*06h*/{ pcit_ive, 0, 1 },
  /*07h*/{ "ImpVar", 0, 3 },
  /*08h*/{ pcit_ive, 0, 1 },
  /*09h*/{ "EqvUI1", PCT_NONE, 1 },
  /*0Ah*/{ "EqvI4", PCT_NONE, 1 },
  /*0Bh*/{ "EqvI4", PCT_NONE, 1 },
  /*0Ch*/{ pcit_ive, 0, 1 },
  /*0Dh*/{ pcit_ive, 0, 1 },
  /*0Eh*/{ pcit_ive, 0, 1 },
  /*0Fh*/{ "EqvVar", 0, 3 },
  /*10h*/{ pcit_ive, 0, 1 },
  /*11h*/{ "XorI4", PCT_NONE, 1 },
  /*12h*/{ "XorI4", PCT_NONE, 1 },
  /*13h*/{ "XorI4", PCT_NONE, 1 },
  /*14h*/{ pcit_ive, 0, 1 },
  /*15h*/{ pcit_ive, 0, 1 },
  /*16h*/{ pcit_ive, 0, 1 },
  /*17h*/{ "XorVar", 0, 3 },
  /*18h*/{ pcit_ive, 0, 1 },
  /*19h*/{ "OrI2", PCT_NONE, 1 },
  /*1Ah*/{ "OrI2", PCT_NONE, 1 },
  /*1Bh*/{ "OrI2", PCT_NONE, 1 },
  /*1Ch*/{ pcit_ive, 0, 1 },
  /*1Dh*/{ pcit_ive, 0, 1 },
  /*1Eh*/{ pcit_ive, 0, 1 },
  /*1Fh*/{ "OrVar", 0, 3 },
  /*20h*/{ pcit_ive, 0, 1 },
  /*21h*/{ "AndUI1", PCT_NONE, 1 },
  /*22h*/{ "AndUI1", PCT_NONE, 1 },
  /*23h*/{ "AndUI1", PCT_NONE, 1 },
  /*24h*/{ pcit_ive, 0, 1 },
  /*25h*/{ pcit_ive, 0, 1 },
  /*26h*/{ pcit_ive, 0, 1 },
  /*27h*/{ "AndVar", 0, 3 },
  /*28h*/{ pcit_ive, 0, 1 },
  /*29h*/{ "EqI2", PCT_NONE, 1 },
  /*2Ah*/{ "EqI2", PCT_NONE, 1 },
  /*2Bh*/{ "EqI4", PCT_NONE, 1 },
  /*2Ch*/{ "EqR8", PCT_NONE, 1 },
  /*2Dh*/{ "EqR8", PCT_NONE, 1 },
  /*2Eh*/{ "EqCy", PCT_NONE, 1 },
  /*2Fh*/{ "EqVar", 0, 3 },
  /*30h*/{ "EqStr", PCT_NONE, 1 },
  /*31h*/{ "EqTextVar", 0, 3 },
  /*32h*/{ "EqTextStr", PCT_NONE, 1 },
  /*33h*/{ "EqVarBool", PCT_NONE, 1 },
  /*34h*/{ "EqTextVarBool", PCT_NONE, 1 },
  /*35h*/{ "EqCyR8", PCT_NONE, 1 },
  /*36h*/{ "NeUI1", PCT_NONE, 1 },
  /*37h*/{ "NeUI1", PCT_NONE, 1 },
  /*38h*/{ "NeI4", PCT_NONE, 1 },
  /*39h*/{ "NeR4", PCT_NONE, 1 },
  /*3Ah*/{ "NeR4", PCT_NONE, 1 },
  /*3Bh*/{ "NeCy", PCT_NONE, 1 },
  /*3Ch*/{ "NeVar", 0, 3 },
  /*3Dh*/{ "NeStr", PCT_NONE, 1 },
  /*3Eh*/{ "NeTextVar", 0, 3 },
  /*3Fh*/{ "NeTextStr", PCT_NONE, 1 },
  /*40h*/{ "NeVarBool", PCT_NONE, 1 },
  /*41h*/{ "NeTextVarBool", PCT_NONE, 1 },
  /*42h*/{ "NeCyR8", PCT_NONE, 1 },
  /*43h*/{ "LeUI1", PCT_NONE, 1 },
  /*44h*/{ "LeI2", PCT_NONE, 1 },
  /*45h*/{ "LeI4", PCT_NONE, 1 },
  /*46h*/{ "LeR4", PCT_NONE, 1 },
  /*47h*/{ "LeR4", PCT_NONE, 1 },
  /*48h*/{ "LeCy", PCT_NONE, 1 },
  /*49h*/{ "LeVar", 0, 3 },
  /*4Ah*/{ "LeStr", PCT_NONE, 1 },
  /*4Bh*/{ "LeTextVar", 0, 3 },
  /*4Ch*/{ "LeTextStr", PCT_NONE, 1 },
  /*4Dh*/{ "LeVarBool", PCT_NONE, 1 },
  /*4Eh*/{ "LeTextVarBool", PCT_NONE, 1 },
  /*4Fh*/{ "LeCyR8", PCT_NONE, 1 },
  /*50h*/{ "GeUI1", PCT_NONE, 1 },
  /*51h*/{ "GeI2", PCT_NONE, 1 },
  /*52h*/{ "GeI4", PCT_NONE, 1 },
  /*53h*/{ "GeR4", PCT_NONE, 1 },
  /*54h*/{ "GeR4", PCT_NONE, 1 },
  /*55h*/{ "GeCy", PCT_NONE, 1 },
  /*56h*/{ "GeVar", 0, 3 },
  /*57h*/{ "GeStr", PCT_NONE, 1 },
  /*58h*/{ "GeTextVar", 0, 3 },
  /*59h*/{ "GeTextStr", PCT_NONE, 1 },
  /*5Ah*/{ "GeVarBool", PCT_NONE, 1 },
  /*5Bh*/{ "GeTextVarBool", PCT_NONE, 1 },
  /*5Ch*/{ "GeCyR8", PCT_NONE, 1 },
  /*5Dh*/{ "LtUI1", PCT_NONE, 1 },
  /*5Eh*/{ "LtI2", PCT_NONE, 1 },
  /*5Fh*/{ "LtI4", PCT_NONE, 1 },
  /*60h*/{ "LtR4", PCT_NONE, 1 },
  /*61h*/{ "LtR4", PCT_NONE, 1 },
  /*62h*/{ "LtCy", PCT_NONE, 1 },
  /*63h*/{ "LtVar", 0, 3 },
  /*64h*/{ "LtStr", PCT_NONE, 1 },
  /*65h*/{ "LtTextVar", 0, 3 },
  /*66h*/{ "LtTextStr", PCT_NONE, 1 },
  /*67h*/{ "LtVarBool", PCT_NONE, 1 },
  /*68h*/{ "LtTextVarBool", PCT_NONE, 1 },
  /*69h*/{ "LtCyR8", PCT_NONE, 1 },
  /*6Ah*/{ "GtUI1", PCT_NONE, 1 },
  /*6Bh*/{ "GtI2", PCT_NONE, 1 },
  /*6Ch*/{ "GtI4", PCT_NONE, 1 },
  /*6Dh*/{ "GtR4", PCT_NONE, 1 },
  /*6Eh*/{ "GtR4", PCT_NONE, 1 },
  /*6Fh*/{ "GtCy", PCT_NONE, 1 },
  /*70h*/{ "GtVar", 0, 3 },
  /*71h*/{ "GtStr", PCT_NONE, 1 },
  /*72h*/{ "GtTextVar", 0, 3 },
  /*73h*/{ "GtTextStr", PCT_NONE, 1 },
  /*74h*/{ "GtVarBool", PCT_NONE, 1 },
  /*75h*/{ "GtTextVarBool", PCT_NONE, 1 },
  /*76h*/{ "GtCyR8", PCT_NONE, 1 },
  /*77h*/{ pcit_ive, 0, 1 },
  /*78h*/{ pcit_ive, 0, 1 },
  /*79h*/{ pcit_ive, 0, 1 },
  /*7Ah*/{ pcit_ive, 0, 1 },
  /*7Bh*/{ pcit_ive, 0, 1 },
  /*7Ch*/{ pcit_ive, 0, 1 },
  /*7Dh*/{ "LikeVar", 0, 3 },
  /*7Eh*/{ "LikeStr", PCT_NONE, 1 },
  /*7Fh*/{ "LikeTextVar", 0, 3 },
  /*80h*/{ "LikeTextStr", PCT_NONE, 1 },
  /*81h*/{ "LikeVarBool", PCT_NONE, 1 },
  /*82h*/{ "LikeTextVarBool", PCT_NONE, 1 },
  /*83h*/{ pcit_ive, 0, 1 },
  /*84h*/{ "BetweenUI1", PCT_NONE, 1 },
  /*85h*/{ "BetweenI2", PCT_NONE, 1 },
  /*86h*/{ "BetweenI4", PCT_NONE, 1 },
  /*87h*/{ "BetweenR4", PCT_NONE, 1 },
  /*88h*/{ "BetweenR4", PCT_NONE, 1 },
  /*89h*/{ "BetweenCy", PCT_NONE, 1 },
  /*8Ah*/{ "BetweenVar", PCT_NONE, 1 },
  /*8Bh*/{ "BetweenStr", PCT_NONE, 1 },
  /*8Ch*/{ "BetweenTextVar", PCT_NONE, 1 },
  /*8Dh*/{ "BetweenTextStr", PCT_NONE, 1 },
  /*8Eh*/{ "AddUI1", PCT_NONE, 1 },
  /*8Fh*/{ "AddI2", PCT_NONE, 1 },
  /*90h*/{ "AddI4", PCT_NONE, 1 },
  /*91h*/{ "AddR4", PCT_NONE, 1 },
  /*92h*/{ "AddR4", PCT_NONE, 1 },
  /*93h*/{ "AddCy", PCT_NONE, 1 },
  /*94h*/{ "AddVar", 0, 3 },
  /*95h*/{ pcit_ive, 0, 1 },
  /*96h*/{ "SubUI1", PCT_NONE, 1 },
  /*97h*/{ "SubI2", PCT_NONE, 1 },
  /*98h*/{ "SubI4", PCT_NONE, 1 },
  /*99h*/{ "SubR4", PCT_NONE, 1 },
  /*9Ah*/{ "SubR4", PCT_NONE, 1 },
  /*9Bh*/{ "SubCy", PCT_NONE, 1 },
  /*9Ch*/{ "SubVar", 0, 3 },
  /*9Dh*/{ pcit_ive, 0, 1 },
  /*9Eh*/{ "ModUI1", PCT_NONE, 1 },
  /*9Fh*/{ "ModI2", PCT_NONE, 1 },
  /*A0h*/{ "ModI4", PCT_NONE, 1 },
  /*A1h*/{ pcit_ive, 0, 1 },
  /*A2h*/{ pcit_ive, 0, 1 },
  /*A3h*/{ pcit_ive, 0, 1 },
  /*A4h*/{ "ModVar", 0, 3 },
  /*A5h*/{ pcit_ive, 0, 1 },
  /*A6h*/{ "IDvUI1", PCT_NONE, 1 },
  /*A7h*/{ "IDvI2", PCT_NONE, 1 },
  /*A8h*/{ "IDvI4", PCT_NONE, 1 },
  /*A9h*/{ pcit_ive, 0, 1 },
  /*AAh*/{ pcit_ive, 0, 1 },
  /*ABh*/{ pcit_ive, 0, 1 },
  /*ACh*/{ "IDvVar", 0, 3 },
  /*ADh*/{ pcit_unk, 0, 1 },
  /*AEh*/{ "MulUI1", PCT_NONE, 1 },
  /*AFh*/{ "MulI2", PCT_NONE, 1 },
  /*B0h*/{ "MulI4", PCT_NONE, 1 },
  /*B1h*/{ "MulR4", PCT_NONE, 1 },
  /*B2h*/{ "MulR4", PCT_NONE, 1 },
  /*B3h*/{ "MulCy", PCT_NONE, 1 },
  /*B4h*/{ "MulVar", 0, 3 },
  /*B5h*/{ pcit_ive, 0, 1 },
  /*B6h*/{ pcit_ive, 0, 1 },
  /*B7h*/{ pcit_ive, 0, 1 },
  /*B8h*/{ pcit_ive, 0, 1 },
  /*B9h*/{ "DivR8", PCT_NONE, 1 },
  /*BAh*/{ "DivR8", PCT_NONE, 1 },
  /*BBh*/{ pcit_ive, 0, 1 },
  /*BCh*/{ "DivVar", 0, 3 },
  /*BDh*/{ pcit_ive, 0, 1 },
  /*BEh*/{ "NotUI1", PCT_NONE, 1 },
  /*BFh*/{ "NotI4", PCT_NONE, 1 },
  /*C0h*/{ "NotI4", PCT_NONE, 1 },
  /*C1h*/{ pcit_ive, 0, 1 },
  /*C2h*/{ pcit_ive, 0, 1 },
  /*C3h*/{ pcit_ive, 0, 1 },
  /*C4h*/{ "NotVar", 0, 3 },
  /*C5h*/{ pcit_ive, 0, 1 },
  /*C6h*/{ pcit_ive, 0, 1 },
  /*C7h*/{ "UMiI2", PCT_NONE, 1 },
  /*C8h*/{ "UMiI2", PCT_NONE, 1 },
  /*C9h*/{ "UMiR4", PCT_NONE, 1 },
  /*CAh*/{ "UMiR4", PCT_NONE, 1 },
  /*CBh*/{ "UMiCy", PCT_NONE, 1 },
  /*CCh*/{ "UMiVar", 0, 3 },
  /*CDh*/{ pcit_ive, 0, 1 },
  /*CEh*/{ "PwrVar", 0, 3 },
  /*CFh*/{ "PwrR8R8", PCT_NONE, 1 },
  /*D0h*/{ "PwrR8I2", PCT_NONE, 1 },
  /*D1h*/{ "MulCyI2", PCT_NONE, 1 },
  /*D2h*/{ pcit_ive, PCT_NONE, 1 },
  /*D3h*/{ pcit_ive, 0, 1 },
  /*D4h*/{ "FnAbsI2", PCT_NONE, 1 },
  /*D5h*/{ "FnAbsI4", PCT_NONE, 1 },
  /*D6h*/{ "FnAbsR4", PCT_NONE, 1 },
  /*D7h*/{ "FnAbsR4", PCT_NONE, 1 },
  /*D8h*/{ "FnAbsCy", PCT_NONE, 1 },
  /*D9h*/{ "FnAbsVar", 0, 3 },
  /*DAh*/{ pcit_ive, 0, 1 },
  /*DBh*/{ pcit_ive, 0, 1 },
  /*DCh*/{ pcit_ive, 0, 1 },
  /*DDh*/{ pcit_ive, 0, 1 },
  /*DEh*/{ "FnFixR8", PCT_NONE, 1 },
  /*DFh*/{ "FnFixR8", PCT_NONE, 1 },
  /*E0h*/{ "FnFixCy", PCT_NONE, 1 },
  /*E1h*/{ "FnFixVar", 0, 3 },
  /*E2h*/{ pcit_ive, 0, 1 },
  /*E3h*/{ pcit_ive, 0, 1 },
  /*E4h*/{ pcit_ive, 0, 1 },
  /*E5h*/{ pcit_ive, 0, 1 },
  /*E6h*/{ "FnIntR8", PCT_NONE, 1 },
  /*E7h*/{ "FnIntR8", PCT_NONE, 1 },
  /*E8h*/{ "FnIntCy", PCT_NONE, 1 },
  /*E9h*/{ "FnIntVar", 0, 3 },
  /*EAh*/{ pcit_ive, 0, 1 },
  /*EBh*/{ "FnLenVar", 0, 3 },
  /*ECh*/{ "FnLenStr", PCT_NONE, 1 },
  /*EDh*/{ "FnLenBVar", 0, 3 },
  /*EEh*/{ "FnLenBStr", PCT_NONE, 1 },
  /*EFh*/{ "ConcatVar", 0, 3 },
  /*F0h*/{ "ConcatStr", PCT_NONE, 1 },
  /*F1h*/{ pcit_ive, 0, 1 },
  /*F2h*/{ "FnSgnUI1", PCT_NONE, 1 },
  /*F3h*/{ "FnSgnUI1", PCT_NONE, 1 },
  /*F4h*/{ "FnSgnI4", PCT_NONE, 1 },
  /*F5h*/{ "FnSgnR8", PCT_NONE, 1 },
  /*F6h*/{ "FnSgnR4", PCT_NONE, 1 },
  /*F7h*/{ "FnSgnCy", PCT_NONE, 1 },
  /*F8h*/{ pcit_ive, 0, 1 },
  /*F9h*/{ pcit_ive, 0, 1 },
  /*FAh*/{ "SeekFile", PCT_NONE, 1 },
  /*FBh*/{ "NameFile", PCT_NONE, 1 },
  /*FCh*/{ "CStrI2", PCT_NONE, 1 },
  /*FDh*/{ "CStrUI1", PCT_NONE, 1 },
  /*FEh*/{ "CStrI4", PCT_NONE, 1 },
  /*FFh*/{ "CStrR4", PCT_NONE, 1 }
};

/*P-Code 双字节指令集1 (扩展指令集) 0xFC前缀*/
const VB_PCODE_LEAD_INST PCodeLead1Inst[256] =
{
  /*00h*/{ "CStrR8", 0, 1 },
  /*01h*/{ "CStrCy", PCT_NONE, 1 },
  /*02h*/{ "CStrVar", PCT_NONE, 1 },
  /*03h*/{ pcit_ive, 0, 1 },
  /*04h*/{ "CCyI2", 0, 1 },
  /*05h*/{ "CCyI2", 0, 1 },
  /*06h*/{ "CCyI4", 0, 1 },
  /*07h*/{ "CCyR4", 0, 1 },
  /*08h*/{ "CCyR4", 0, 1 },
  /*09h*/{ pcit_ive, 0, 1 },
  /*0Ah*/{ "CCyVar", PCT_NONE, 1 },
  /*0Bh*/{ "CCyStr", PCT_NONE, 1 },
  /*0Ch*/{ pcit_ive, 0, 1 },
  /*0Dh*/{ "CUI1I2", 0, 1 },
  /*0Eh*/{ "CUI1I4", 0, 1 },
  /*0Fh*/{ "CUI1R4", 0, 1 },
  /*10h*/{ "CUI1R4", 0, 1 },
  /*11h*/{ "CUI1Cy", PCT_NONE, 1 },
  /*12h*/{ "CUI1Var", PCT_NONE, 1 },
  /*13h*/{ "CUI1Str", PCT_NONE, 1 },
  /*14h*/{ "CI2UI1", 0, 1 },
  /*15h*/{ pcit_ive, 0, 1 },
  /*16h*/{ "CI2I4", 0, 1 },
  /*17h*/{ "CI2R8", 0, 1 },
  /*18h*/{ "CI2R8", 0, 1 },
  /*19h*/{ "CI2Cy", PCT_NONE, 1 },
  /*1Ah*/{ "CI2Var", PCT_NONE, 1 },
  /*1Bh*/{ "CI2Str", PCT_NONE, 1 },
  /*1Ch*/{ "CI4UI1", 0, 1 },
  /*1Dh*/{ "CI4UI1", 0, 1 },
  /*1Eh*/{ pcit_ive, 0, 1 },
  /*1Fh*/{ "CI4R8", 0, 1 },
  /*20h*/{ "CI4R8", 0, 1 },
  /*21h*/{ "CI4Cy", PCT_NONE, 1 },
  /*22h*/{ "CI4Var", PCT_NONE, 1 },
  /*23h*/{ "CI4Str", PCT_NONE, 1 },
  /*24h*/{ "FnCSngI2", 0, 1 },
  /*25h*/{ "FnCSngI2", 0, 1 },
  /*26h*/{ "CR4I4", 0, 1 },
  /*27h*/{ "CR4R8", 0, 1 },
  /*28h*/{ "CR4R8", 0, 1 },
  /*29h*/{ "CR8Cy", PCT_NONE, 1 },
  /*2Ah*/{ "CR8Var", PCT_NONE, 1 },
  /*2Bh*/{ "CR4Str", PCT_NONE, 1 },
  /*2Ch*/{ "FnCSngI2", PCT_NONE, 1 },
  /*2Dh*/{ "FnCSngI2", PCT_NONE, 1 },
  /*2Eh*/{ "CR4I4", PCT_NONE, 1 },
  /*2Fh*/{ "CR8R4", 0, 1 },
  /*30h*/{ "CR8R4", PCT_NONE, 1 },
  /*31h*/{ "CR8Cy", 0, 1 },
  /*32h*/{ "CR8Var", PCT_NONE, 1 },
  /*33h*/{ "CR8Str", PCT_NONE, 1 },
  /*34h*/{ "CAdVar", PCT_NONE, 1 },
  /*35h*/{ "CRefVarAry", PCT_NONE, 1 },
  /*36h*/{ pcit_ive, 0, 1 },
  /*37h*/{ pcit_ive, 0, 1 },
  /*38h*/{ "CUI1Bool", PCT_NONE, 1 },
  /*39h*/{ "FnCDblCy", PCT_NONE, 1 },
  /*3Ah*/{ "FnCDblR8", PCT_NONE, 1 },
  /*3Bh*/{ "FnCDblR8", PCT_NONE, 1 },
  /*3Ch*/{ "FnCSngI2", 0, 1 },
  /*3Dh*/{ "FnCSngI2", PCT_NONE, 1 },
  /*3Eh*/{ "FnCSngI4", 0, 1 },
  /*3Fh*/{ "CSng", PCT_NONE, 1 },
  /*40h*/{ "CSng", PCT_NONE, 1 },
  /*41h*/{ "FnCSngCy", PCT_NONE, 1 },
  /*42h*/{ "FnCSngVar", PCT_NONE, 1 },
  /*43h*/{ "FnCSngStr", PCT_NONE, 1 },
  /*44h*/{ "FnCByteVar", PCT_NONE, 1 },
  /*45h*/{ "FnCIntVar", PCT_NONE, 1 },
  /*46h*/{ "FnCLngVar", PCT_NONE, 1 },
  /*47h*/{ "CDateR8", PCT_NONE, 1 },
  /*48h*/{ "FnCDblVar", PCT_NONE, 1 },
  /*49h*/{ "FnCCurVar", 0, 1 },
  /*4Ah*/{ pcit_ive, 0, 1 },
  /*4Bh*/{ "FnCStrVar", 0, 1 },
  /*4Ch*/{ pcit_ive, 0, 1 },
  /*4Dh*/{ "FnCBoolVar", PCT_NONE, 1 },
  /*4Eh*/{ "FnCDateVar", PCT_NONE, 1 },
  /*4Fh*/{ "FnCDateVar", PCT_NONE, 1 },
  /*50h*/{ "CBoolUI1", PCT_NONE, 1 },
  /*51h*/{ "CBoolUI1", PCT_NONE, 1 },
  /*52h*/{ "CBoolI4", PCT_NONE, 1 },
  /*53h*/{ "CBoolR4", PCT_NONE, 1 },
  /*54h*/{ "CBoolR4", PCT_NONE, 1 },
  /*55h*/{ "CBoolCy", PCT_NONE, 1 },
  /*56h*/{ "CBoolVar", 0, 1 },
  /*57h*/{ "CBoolStr", PCT_NONE, 1 },
  /*58h*/{ "CStr2Uni", 0, 1 },
  /*59h*/{ "CStrAry2Uni", PCT_NONE, 1 },
  /*5Ah*/{ "CStr2Ansi", PCT_NONE, 1 },
  /*5Bh*/{ "CStrAry2Ansi", PCT_NONE, 1 },
  /*5Ch*/{ "PopAdLd4", PCT_NONE, 1 },
  /*5Dh*/{ "CRecAnsi2Uni", 0, 3 },
  /*5Eh*/{ "CRecUni2Ansi", 0, 3 },
  /*5Fh*/{ "CStr2Vec", 0, 3 },
  /*60h*/{ "CVar2Vec", 0, 3 },
  /*61h*/{ "CVec2Var", 0, 5 },
  /*62h*/{ "SetLastError", PCT_NONE, 1 },
  /*63h*/{ "LitNothing", 0, 1 },
  /*64h*/{ "LitVar_Null", 0, 2 },
  /*65h*/{ "LitVar_TRUE", 0, 3 },
  /*66h*/{ "LitVar_FALSE", 0, 3 },
  /*67h*/{ "LitVar_Empty", 0, 3 },
  /*68h*/{ "LitVar_Missing", 0, 3 },
  /*69h*/{ "VCallHresult", 0, 5 },
  /*6Ah*/{ "ThisVCallHresult", 0, 5 },
  /*6Bh*/{ pcit_ive, 0, 1 },
  /*6Ch*/{ pcit_ive, 0, 1 },
  /*6Dh*/{ "ExitProcHresult", PCT_NONE, 1 },
  /*6Eh*/{ pcit_ive, 0, 1 },
  /*6Fh*/{ "CheckTypeVar", 0, 3 },
  /*70h*/{ pcit_ive, 0, 1 },
  /*71h*/{ "CUnkVar", PCT_NONE, 1 },
  /*72h*/{ "CVarUnk", 0, 3 },
  /*73h*/{ "LdPrUnkVar", PCT_NONE, 1 },
  /*74h*/{ "FLdLateIdUnkVar", 0, 9 },
  /*75h*/{ "GetRec3", PCT_NONE, 1 },
  /*76h*/{ "GetRec4", PCT_NONE, 1 },
  /*77h*/{ "PutRec3", 0, 1 },
  /*78h*/{ "PutRec4", 0, 1 },
  /*79h*/{ "GetRecOwner3", 0, -1 },
  /*7Ah*/{ "GetRecOwner4", 0, -1 },
  /*7Bh*/{ "PutRecOwner3", 0, -1 },
  /*7Ch*/{ "PutRecOwner4", 0, -1 },
  /*7Dh*/{ "Input", 0, 1 },
  /*7Eh*/{ "InputDone", PCT_NONE, 1 },
  /*7Fh*/{ "InputItemUI1", 0, 1 },
  /*80h*/{ "InputItemI2", PCT_NONE, 1 },
  /*81h*/{ "InputItemI4", PCT_NONE, 1 },
  /*82h*/{ "InputItemR4", PCT_NONE, 1 },
  /*83h*/{ "InputItemR8", 0, 1 },
  /*84h*/{ "InputItemCy", PCT_NONE, 1 },
  /*85h*/{ "InputItemVar", PCT_NONE, 1 },
  /*86h*/{ "InputItemStr", PCT_NONE, 1 },
  /*87h*/{ "InputItemBool", PCT_NONE, 1 },
  /*88h*/{ "InputItemDate", PCT_NONE, 1 },
  /*89h*/{ "PopFPR4", PCT_NONE, 1 },
  /*8Ah*/{ "PopFPR8", PCT_NONE, 1 },
  /*8Bh*/{ "PopAd", PCT_NONE, 1 },
  /*8Ch*/{ "PopAdLdVar", PCT_NONE, 1 },
  /*8Dh*/{ "AryLdPr", 0, 3 },
  /*8Eh*/{ "AryLdRf", 0, 3 },
  /*8Fh*/{ "ParmAry1St", 0, 5 },
  /*90h*/{ "Ary1LdUI1", PCT_NONE, 1 },
  /*91h*/{ "Ary1LdI2", PCT_NONE, 1 },
  /*92h*/{ "Ary1LdI4", PCT_NONE, 1 },
  /*93h*/{ "Ary1LdI4", PCT_NONE, 1 },
  /*94h*/{ "Ary1LdR8", 0, 1 },
  /*95h*/{ "Ary1LdR8", 0, 1 },
  /*96h*/{ "Ary1LdRfVar", PCT_NONE, 1 },
  /*97h*/{ "Ary1LdI4", PCT_NONE, 1 },
  /*98h*/{ "Ary1LdI4", PCT_NONE, 1 },
  /*99h*/{ "Ary1LdFPR4", PCT_NONE, 1 },
  /*9Ah*/{ "Ary1LdFPR8", PCT_NONE, 1 },
  /*9Bh*/{ "Ary1LdPr", PCT_NONE, 1 },
  /*9Ch*/{ "Ary1LdRf", 0, 1 },
  /*9Dh*/{ "Ary1LdVar", 0, 1 },
  /*9Eh*/{ pcit_ive, 0, 1 },
  /*9Fh*/{ pcit_ive, 0, 1 },
  /*A0h*/{ "Ary1StUI1", PCT_NONE, 1 },
  /*A1h*/{ "Ary1StI2", 0, 1 },
  /*A2h*/{ "Ary1StR4", 0, 1 },
  /*A3h*/{ "Ary1StR4", 0, 1 },
  /*A4h*/{ "Ary1StCy", 0, 1 },
  /*A5h*/{ "Ary1StCy", 0, 1 },
  /*A6h*/{ "Ary1StVar", PCT_NONE, 1 },
  /*A7h*/{ "Ary1StStr", PCT_NONE, 1 },
  /*A8h*/{ "Ary1StAd", PCT_NONE, 1 },
  /*A9h*/{ "Ary1StFPR4", 0, 1 },
  /*AAh*/{ "Ary1StFPR8", 0, 1 },
  /*ABh*/{ "Ary1StVarAd", 0, 1 },
  /*ACh*/{ "Ary1StVarAdFunc", 0, 1 },
  /*ADh*/{ "Ary1StVarUnk", 0, 1 },
  /*AEh*/{ "Ary1StVarUnkFunc", PCT_NONE, 1 },
  /*AFh*/{ "Ary1StAdFunc", PCT_NONE, 1 },
  /*B0h*/{ "Ary1StVarCopy", PCT_NONE, 1 },
  /*B1h*/{ "Ary1StStrCopy", PCT_NONE, 1 },
  /*B2h*/{ "Ary1LdRfVarg", 0, 3 },
  /*B3h*/{ "Ary1LdVarg", PCT_NONE, 1 },
  /*B4h*/{ "Ary1LdRfVargParam", 0, 1 },
  /*B5h*/{ "Ary1StVarg", 0, 1 },
  /*B6h*/{ "Ary1StVargCopy", 0, 1 },
  /*B7h*/{ "Ary1StVargAd", 0, 1 },
  /*B8h*/{ "Ary1StVargAdFunc", 0, 1 },
  /*B9h*/{ "Ary1StVargUnk", PCT_NONE, 1 },
  /*BAh*/{ "Ary1StVargUnkFunc", PCT_NONE, 1 },
  /*BBh*/{ "MidVar", 0, 1 },
  /*BCh*/{ "MidBStr", 0, 3 },
  /*BDh*/{ "MidBVar", 0, 1 },
  /*BEh*/{ "MidBStrB", 0, 3 },
  /*BFh*/{ "LineInputVar", PCT_NONE, 1 },
  /*C0h*/{ "LineInputStr", PCT_NONE, 1 },
  /*C1h*/{ "Error", 0, 1 },
  /*C2h*/{ "Stop", 0, 1 },
  /*C3h*/{ "Erase", 0, 1 },
  /*C4h*/{ "LargeBos", 0, 2 },
  /*C5h*/{ pcit_ive, 0, 1 },
  /*C6h*/{ pcit_ive, 0, 1 },
  /*C7h*/{ pcit_ive, 0, 1 },
  /*C8h*/{ "End", PCT_NONE, 1 },
  /*C9h*/{ "Return", PCT_NONE, 1 },
  /*CAh*/{ "FnLBound", PCT_NONE, 1 },
  /*CBh*/{ "FnUBound", PCT_NONE, 1 },
  /*CCh*/{ "ExitProcUI1", 0, 1 },
  /*CDh*/{ "ExitProcI2", 0, 1 },
  /*CEh*/{ "ExitProcStr", 0, 1 },
  /*CFh*/{ "ExitProcR4", PCT_NONE, 1 },
  /*D0h*/{ "ExitProcR8", PCT_NONE, 1 },
  /*D1h*/{ "ExitProcCy", PCT_NONE, 1 },
  /*D2h*/{ pcit_ive, 0, 1 },
  /*D3h*/{ "ExitProcStr", 0, 1 },
  /*D4h*/{ "ExitProcStr", PCT_NONE, 1 },
  /*D5h*/{ "ExitProcStr", PCT_NONE, 1 },
  /*D6h*/{ pcit_ive, 0, 1 },
  /*D7h*/{ pcit_ive, 0, 1 },
  /*D8h*/{ pcit_ive, 0, 1 },
  /*D9h*/{ pcit_ive, 0, 1 },
  /*DAh*/{ pcit_ive, 0, 1 },
  /*DBh*/{ pcit_ive, 0, 1 },
  /*DCh*/{ pcit_ive, 0, 1 },
  /*DDh*/{ pcit_ive, 0, 1 },
  /*DEh*/{ pcit_ive, 0, 1 },
  /*DFh*/{ pcit_ive, 0, 1 },
  /*E0h*/{ "FLdUI1", 0, 3 },
  /*E1h*/{ "FLdI2", 0, 3 },
  /*E2h*/{ "FLdR4", 0, 3 },
  /*E3h*/{ "FLdR4", 0, 3 },
  /*E4h*/{ "FLdR8", 0, 3 },
  /*E5h*/{ "FLdR8", 0, 3 },
  /*E6h*/{ "FLdRfVar", 0, 3 },
  /*E7h*/{ "FLdR4", 0, 3 },
  /*E8h*/{ "FLdR4", 0, 3 },
  /*E9h*/{ "FLdFPR4", 0, 3 },
  /*EAh*/{ "FLdFPR8", 0, 3 },
  /*EBh*/{ "FLdPr", 0, 3 },
  /*ECh*/{ "FLdRfVar", 0, 3 },
  /*EDh*/{ "FLdVar", 0, 3 },
  /*EEh*/{ pcit_ive, 0, 1 },
  /*EFh*/{ pcit_ive, 0, 1 },
  /*F0h*/{ "FStUI1", 0, 3 },
  /*F1h*/{ "FStI2", 0, 3 },
  /*F2h*/{ "FStR4", 0, 3 },
  /*F3h*/{ "FStR4", 0, 3 },
  /*F4h*/{ "FStR8", 0, 3 },
  /*F5h*/{ "FStR8", 0, 3 },
  /*F6h*/{ "FStVar", 0, 3 },
  /*F7h*/{ "FStStr", 0, 3 },
  /*F8h*/{ "FStAd", 0, 3 },
  /*F9h*/{ "FStFPR4", 0, 3 },
  /*FAh*/{ "FStFPR8", 0, 3 },
  /*FBh*/{ "FStVarAd", 0, 3 },
  /*FCh*/{ "FStVarAdFunc", 0, 3 },
  /*FDh*/{ "FStVarUnk", 0, 3 },
  /*FEh*/{ "FStVarUnkFunc", 0, 3 },
  /*FFh*/{ "FStAdFunc", 0, 3 }
};

/*P-Code 双字节指令集2 (扩展指令集) 0xFD前缀*/
const VB_PCODE_LEAD_INST PCodeLead2Inst[256] =
{
  /*00h*/{ "FStVarCopy", 0, 3 },
  /*01h*/{ "FStStrCopy", 0, 3 },
  /*02h*/{ "HardType", PCT_NONE, 1 },
  /*03h*/{ "Branch", 0, 3 },
  /*04h*/{ "BranchF", 0, 3 },
  /*05h*/{ "BranchFVar", 0, 3 },
  /*06h*/{ "BranchFVarFree", 0, 3 },
  /*07h*/{ "BranchT", 0, 3 },
  /*08h*/{ "BranchTVar", 0, 3 },
  /*09h*/{ "BranchTVarFree", 0, 3 },
  /*0Ah*/{ "Gosub", 0, 3 },
  /*0Bh*/{ "OnErrorGoto", 0, 3 },
  /*0Ch*/{ "Resume", 0, 3 },
  /*0Dh*/{ "AryLock", 0, 3 },
  /*0Eh*/{ "AryUnlock", 0, 3 },
  /*0Fh*/{ "AryDescTemp", 0, 3 },
  /*10h*/{ "ILdUI1", 0, 3 },
  /*11h*/{ "ILdI2", 0, 3 },
  /*12h*/{ "ILdAd", 0, 3 },
  /*13h*/{ "ILdAd", 0, 3 },
  /*14h*/{ "ILdR8", 0, 3 },
  /*15h*/{ "ILdR8", 0, 3 },
  /*16h*/{ "ILdRfDarg", 0, 5 },
  /*17h*/{ "ILdAd", 0, 3 },
  /*18h*/{ "ILdAd", 0, 3 },
  /*19h*/{ "ILdFPR4", 0, 3 },
  /*1Ah*/{ "ILdFPR8", 0, 3 },
  /*1Bh*/{ "ILdPr", 0, 3 },
  /*1Ch*/{ "FLdR4", 0, 3 },
  /*1Dh*/{ "ILdDarg", 0, 3 },
  /*1Eh*/{ pcit_ive, 0, 1 },
  /*1Fh*/{ pcit_ive, 0, 1 },
  /*20h*/{ "IStUI1", 0, 3 },
  /*21h*/{ "IStI2", 0, 3 },
  /*22h*/{ "IStI4", 0, 3 },
  /*23h*/{ "IStI4", 0, 3 },
  /*24h*/{ "IStR8", 0, 3 },
  /*25h*/{ "IStR8", 0, 3 },
  /*26h*/{ "IStDarg", 0, 3 },
  /*27h*/{ "IStStr", 0, 3 },
  /*28h*/{ "IStAd", 0, 3 },
  /*29h*/{ "IStFPR4", 0, 3 },
  /*2Ah*/{ "IStFPR8", 0, 3 },
  /*2Bh*/{ "IStDargAd", 0, 3 },
  /*2Ch*/{ "IStDargAdFunc", 0, 3 },
  /*2Dh*/{ "IStDargUnk", 0, 3 },
  /*2Eh*/{ "IStDargUnkFunc", 0, 3 },
  /*2Fh*/{ "IStAdFunc", 0, 3 },
  /*30h*/{ "IStDargCopy", 0, 3 },
  /*31h*/{ "IStStrCopy", 0, 3 },
  /*32h*/{ "PrintChan", PCT_NONE, 1 },
  /*33h*/{ "WriteChan", PCT_NONE, 1 },
  /*34h*/{ "PrintComma", PCT_NONE, 1 },
  /*35h*/{ "PrintEos", PCT_NONE, 1 },
  /*36h*/{ "PrintNL", PCT_NONE, 1 },
  /*37h*/{ "PrintItemComma", PCT_NONE, 1 },
  /*38h*/{ "PrintItemSemi", PCT_NONE, 1 },
  /*39h*/{ "PrintItemNL", PCT_NONE, 1 },
  /*3Ah*/{ "PrintObj", 0, 3 },
  /*3Bh*/{ "PrintSpc", PCT_NONE, 1 },
  /*3Ch*/{ "PrintTab", 0, 1 },
  /*3Dh*/{ "Close", PCT_NONE, 1 },
  /*3Eh*/{ "CloseAll", 0, 1 },
  /*3Fh*/{ "FLdZeroAd", 0, 3 },
  /*40h*/{ "IWMemLdUI1", 0, 3 },
  /*41h*/{ "IWMemLdI2", 0, 3 },
  /*42h*/{ "IWMemLdI4", 0, 3 },
  /*43h*/{ "IWMemLdI4", 0, 3 },
  /*44h*/{ "IWMemLdCy", 0, 3 },
  /*45h*/{ "IWMemLdCy", 0, 3 },
  /*46h*/{ "IWMemLdRfDarg", 0, 5 },
  /*47h*/{ "IWMemLdI4", 0, 3 },
  /*48h*/{ "IWMemLdI4", 0, 3 },
  /*49h*/{ "IWMemLdFPR4", 0, 3 },
  /*4Ah*/{ "IWMemLdFPR8", 0, 3 },
  /*4Bh*/{ "IWMemLdPr", 0, 3 },
  /*4Ch*/{ "IWMemLdRf", 0, 3 },
  /*4Dh*/{ "IWMemLdDarg", 0, 3 },
  /*4Eh*/{ pcit_ive, 0, 1 },
  /*4Fh*/{ pcit_ive, 0, 1 },
  /*50h*/{ "IWMemStUI1", 0, 3 },
  /*51h*/{ "IWMemStI2", 0, 3 },
  /*52h*/{ "IWMemStR4", 0, 3 },
  /*53h*/{ "IWMemStR4", 0, 3 },
  /*54h*/{ "IWMemStCy", 0, 3 },
  /*55h*/{ "IWMemStCy", 0, 3 },
  /*56h*/{ "IWMemStDarg", 0, 3 },
  /*57h*/{ "IWMemStStr", 0, 3 },
  /*58h*/{ "IWMemStAd", 0, 3 },
  /*59h*/{ "IWMemStFPR4", 0, 3 },
  /*5Ah*/{ "IWMemStFPR8", 0, 3 },
  /*5Bh*/{ "IWMemStDargAd", 0, 3 },
  /*5Ch*/{ "IWMemStDargAdFunc", 0, 3 },
  /*5Dh*/{ "IWMemStDargUnk", 0, 3 },
  /*5Eh*/{ "IWMemStDargUnkFunc", 0, 3 },
  /*5Fh*/{ "IWMemStAdFunc", 0, 3 },
  /*60h*/{ "IWMemStDargCopy", 0, 3 },
  /*61h*/{ "IWMemStStrCopy", 0, 3 },
  /*62h*/{ "FLdZeroAd", 0, 3 },
  /*63h*/{ "FStVarNoPop", 0, 3 },
  /*64h*/{ "FStStrNoPop", 0, 3 },
  /*65h*/{ pcit_ive, 0, 1 },
  /*66h*/{ pcit_ive, 0, 1 },
  /*67h*/{ "CVarUI1", 0, 3 },
  /*68h*/{ "CVarI2", 0, 3 },
  /*69h*/{ "CVarI4", 0, 3 },
  /*6Ah*/{ "CVarR4", 0, 3 },
  /*6Bh*/{ "CVarR8", 0, 3 },
  /*6Ch*/{ "CVarCy", 0, 3 },
  /*6Dh*/{ pcit_ive, 0, 1 },
  /*6Eh*/{ "CVarStr", 0, 3 },
  /*6Fh*/{ "CVarAd", 0, 3 },
  /*70h*/{ "MemLdUI1", 0, 3 },
  /*71h*/{ "MemLdI2", 0, 3 },
  /*72h*/{ "MemLdR4", 0, 3 },
  /*73h*/{ "MemLdR4", 0, 3 },
  /*74h*/{ "MemLdR8", 0, 3 },
  /*75h*/{ "MemLdR8", 0, 3 },
  /*76h*/{ "MemLdRfVar", 0, 3 },
  /*77h*/{ "MemLdR4", 0, 3 },
  /*78h*/{ "MemLdR4", 0, 3 },
  /*79h*/{ "MemLdFPR4", 0, 3 },
  /*7Ah*/{ "MemLdFPR8", 0, 3 },
  /*7Bh*/{ "MemLdPr", 0, 3 },
  /*7Ch*/{ "MemLdRfVar", 0, 3 },
  /*7Dh*/{ "MemLdVar", 0, 3 },
  /*7Eh*/{ pcit_ive, 0, 1 },
  /*7Fh*/{ pcit_ive, 0, 1 },
  /*80h*/{ "MemStUI1", 0, 3 },
  /*81h*/{ "MemStI2", 0, 3 },
  /*82h*/{ "MemStR4", 0, 3 },
  /*83h*/{ "MemStR4", 0, 3 },
  /*84h*/{ "MemStCy", 0, 3 },
  /*85h*/{ "MemStCy", 0, 3 },
  /*86h*/{ "MemStVar", 0, 3 },
  /*87h*/{ "MemStStr", 0, 3 },
  /*88h*/{ "MemStAd", 0, 3 },
  /*89h*/{ "MemStFPR4", 0, 3 },
  /*8Ah*/{ "MemStFPR8", 0, 3 },
  /*8Bh*/{ "MemStVarAd", 0, 3 },
  /*8Ch*/{ "MemStVarAdFunc", 0, 3 },
  /*8Dh*/{ "MemStVarUnk", 0, 3 },
  /*8Eh*/{ "MemStVarUnkFunc", 0, 3 },
  /*8Fh*/{ "MemStAdFunc", 0, 3 },
  /*90h*/{ "MemStVarCopy", 0, 3 },
  /*91h*/{ "MemStStrCopy", 0, 3 },
  /*92h*/{ pcit_ive, 0, 1 },
  /*93h*/{ "CDargRef", 0, 3 },
  /*94h*/{ "CVarRef", 0, 5 },
  /*95h*/{ "ExitProcCb", 0, 3 },
  /*96h*/{ "ExitProcCbStack", 0, 3 },
  /*97h*/{ pcit_ive, 0, 1 },
  /*98h*/{ pcit_ive, 0, 1 },
  /*99h*/{ "FFree1Var", PCT_CLEARMEMORY, 3 },
  /*9Ah*/{ "FFree1Str", PCT_ONESTRING, 3 },
  /*9Bh*/{ "FFree1Ad", 0, 3 },
  /*9Ch*/{ "FStAdNoPop", 0, 3 },
  /*9Dh*/{ "FStAdFuncNoPop", 0, 3 },
  /*9Eh*/{ "FLdPrThis", PCT_NONE, 1 },
  /*9Fh*/{ "LdPrVar", PCT_NONE, 1 },
  /*A0h*/{ "ImpAdLdUI1", 0, 3 },
  /*A1h*/{ "ImpAdLdI2", 0, 3 },
  /*A2h*/{ "ImpAdLdStr", 0, 3 },
  /*A3h*/{ "ImpAdLdStr", 0, 3 },
  /*A4h*/{ "ImpAdLdCy", 0, 3 },
  /*A5h*/{ "ImpAdLdCy", 0, 3 },
  /*A6h*/{ "ImpAdLdRf", 0, 3 },
  /*A7h*/{ "ImpAdLdStr", 0, 3 },
  /*A8h*/{ "ImpAdLdStr", 0, 3 },
  /*A9h*/{ "ImpAdLdFPR4", 0, 3 },
  /*AAh*/{ "ImpAdLdFPR8", 0, 3 },
  /*ABh*/{ "ImpAdLdPr", 0, 3 },
  /*ACh*/{ "ImpAdLdRf", 0, 3 },
  /*ADh*/{ "ImpAdLdVar", 0, 3 },
  /*AEh*/{ pcit_ive, 0, 1 },
  /*AFh*/{ pcit_ive, 0, 1 },
  /*B0h*/{ "ImpAdStUI1", 0, 3 },
  /*B1h*/{ "ImpAdStI2", 0, 3 },
  /*B2h*/{ "ImpAdStR4", 0, 3 },
  /*B3h*/{ "ImpAdStR4", 0, 3 },
  /*B4h*/{ "ImpAdStR8", 0, 3 },
  /*B5h*/{ "ImpAdStR8", 0, 3 },
  /*B6h*/{ "ImpAdStVar", 0, 3 },
  /*B7h*/{ "ImpAdStStr", 0, 3 },
  /*B8h*/{ "ImpAdStAd", 0, 3 },
  /*B9h*/{ "ImpAdStFPR4", 0, 3 },
  /*BAh*/{ "ImpAdStFPR8", 0, 3 },
  /*BBh*/{ "ImpAdStVarAd", 0, 3 },
  /*BCh*/{ "ImpAdStVarAdFunc", 0, 3 },
  /*BDh*/{ "ImpAdStVarUnk", 0, 3 },
  /*BEh*/{ "ImpAdStVarUnkFunc", 0, 3 },
  /*BFh*/{ "ImpAdStAdFunc", 0, 3 },
  /*C0h*/{ "ImpAdStVarCopy", 0, 3 },
  /*C1h*/{ "ImpAdStStrCopy", 0, 3 },
  /*C2h*/{ "PopTmpLdAd1", 0, 3 },
  /*C3h*/{ "PopTmpLdAd2", 0, 3 },
  /*C4h*/{ "PopTmpLdAdStr", 0, 3 },
  /*C5h*/{ "PopTmpLdAd8", 0, 3 },
  /*C6h*/{ "PopTmpLdAdVar", 0, 3 },
  /*C7h*/{ "PopTmpLdAdStr", 0, 3 },
  /*C8h*/{ "PopTmpLdAdFPR4", 0, 3 },
  /*C9h*/{ "PopTmpLdAdFPR8", 0, 3 },
  /*CAh*/{ "CopyBytes", 0, 3 },
  /*CBh*/{ "ExitForCollObj", PCT_NONE, 5 },
  /*CCh*/{ "ExitForCollObj", 0, 5 },
  /*CDh*/{ "ExitForCollObj", 0, 5 },
  /*CEh*/{ "ExitForAryVar", 0, 5 },
  /*CFh*/{ "ExitForVar", PCT_NONE, 5 },
  /*D0h*/{ "FMemLdUI1", 0, 5 },
  /*D1h*/{ "FMemLdI2", 0, 5 },
  /*D2h*/{ "FMemLdR4", 0, 5 },
  /*D3h*/{ "FMemLdR4", 0, 5 },
  /*D4h*/{ "FMemLdR8", 0, 5 },
  /*D5h*/{ "FMemLdR8", 0, 5 },
  /*D6h*/{ "FMemLdRf", 0, 5 },
  /*D7h*/{ "FMemLdR4", 0, 5 },
  /*D8h*/{ "FMemLdR4", 0, 5 },
  /*D9h*/{ "FMemLdFPR4", 0, 5 },
  /*DAh*/{ "FMemLdFPR8", 0, 5 },
  /*DBh*/{ "FMemLdPr", 0, 5 },
  /*DCh*/{ "FMemLdRf", 0, 5 },
  /*DDh*/{ "FMemLdVar", 0, 5 },
  /*DEh*/{ pcit_ive, 0, 1 },
  /*DFh*/{ pcit_ive, 0, 1 },
  /*E0h*/{ "FMemStUI1", 0, 5 },
  /*E1h*/{ "FMemStI2", 0, 5 },
  /*E2h*/{ "FMemStR4", 0, 5 },
  /*E3h*/{ "FMemStR4", 0, 5 },
  /*E4h*/{ "FMemStR8", 0, 5 },
  /*E5h*/{ "FMemStR8", 0, 5 },
  /*E6h*/{ "FMemStVar", 0, 5 },
  /*E7h*/{ "FMemStStr", 0, 5 },
  /*E8h*/{ "FMemStAd", 0, 5 },
  /*E9h*/{ "FMemStFPR4", 0, 5 },
  /*EAh*/{ "FMemStFPR8", 0, 5 },
  /*EBh*/{ "FMemStVarAd", 0, 5 },
  /*ECh*/{ "FMemStVarAdFunc", 0, 5 },
  /*EDh*/{ "FMemStVarUnk", 0, 5 },
  /*EEh*/{ "FMemStVarUnkFunc", 0, 5 },
  /*EFh*/{ "FMemStAdFunc", 0, 5 },
  /*F0h*/{ "FMemStVarCopy", 0, 5 },
  /*F1h*/{ "FMemStStrCopy", 0, 5 },
  /*F2h*/{ "CastAd", 0, 3 },
  /*F3h*/{ "CastAdVar", 0, 3 },
  /*F4h*/{ "New", 0, 3 },
  /*F5h*/{ "NewIfNullRf", 0, 3 },
  /*F6h*/{ "NewIfNullAd", 0, 3 },
  /*F7h*/{ "NewIfNullPr", 0, 3 },
  /*F8h*/{ "CVarBoolI2", 0, 3 },
  /*F9h*/{ "CVarDateVar", 0, 3 },
  /*FAh*/{ "CVarErrI4", 0, 3 },
  /*FBh*/{ "CVarDate", 0, 3 },
  /*FCh*/{ "CVarAryVarg", 0, 3 },
  /*FDh*/{ "CStrVarTmp", PCT_NONE, 1 },
  /*FEh*/{ "CStrVarVal", 0, 3 },
  /*FFh*/{ "DestructOFrame", 0, 5 }
};

/*P-Code 双字节指令集3 (扩展指令集) 0xFE前缀*/
const VB_PCODE_LEAD_INST PCodeLead3Inst[256] =
{
  /*00h*/{ "ThisVCallUI1", 0, 3 },
  /*01h*/{ "ThisVCallI2", 0, 3 },
  /*02h*/{ "ThisVCallI2", 0, 3 },
  /*03h*/{ "ThisVCallR4", 0, 3 },
  /*04h*/{ "ThisVCallR8", 0, 3 },
  /*05h*/{ "ThisVCallCy", 0, 3 },
  /*06h*/{ pcit_ive, 0, 1 },
  /*07h*/{ "ThisVCallI2", 0, 3 },
  /*08h*/{ "ThisVCallI2", 0, 3 },
  /*09h*/{ "ThisVCallHidden", 0, 3 },
  /*0Ah*/{ "ThisVCallHidden", 0, 3 },
  /*0Bh*/{ pcit_ive, 0, 1 },
  /*0Ch*/{ "ThisVCallHidden", 0, 3 },
  /*0Dh*/{ "ThisVCallCbFrame", 0, 5 },
  /*0Eh*/{ "StLsetFixStr", 0, 3 },
  /*0Fh*/{ "StFixedStrFree", 0, 3 },
  /*10h*/{ "VCallUI1", 0, 3 },
  /*11h*/{ "VCallStr", 0, 3 },
  /*12h*/{ "VCallStr", 0, 3 },
  /*13h*/{ "VCallR4", 0, 3 },
  /*14h*/{ "VCallR8", 0, 3 },
  /*15h*/{ "VCallCy", 0, 3 },
  /*16h*/{ pcit_ive, 0, 1 },
  /*17h*/{ "VCallStr", 0, 3 },
  /*18h*/{ "VCallStr", 0, 3 },
  /*19h*/{ "VCallFPR8", 0, 3 },
  /*1Ah*/{ "VCallFPR8", 0, 3 },
  /*1Bh*/{ pcit_ive, 0, 1 },
  /*1Ch*/{ "VCallFPR8", 0, 3 },
  /*1Dh*/{ "VCallCbFrame", 0, 5 },
  /*1Eh*/{ "StFixedStrR", 0, 3 },
  /*1Fh*/{ "StFixedStrRFree", 0, 3 },
  /*20h*/{ "ImpAdCallUI1", 0, 5 },
  /*21h*/{ "ImpAdCallI4", 0, 5 },
  /*22h*/{ "ImpAdCallI4", 0, 5 },
  /*23h*/{ "ImpAdCallR4", 0, 5 },
  /*24h*/{ "ImpAdCallR8", 0, 5 },
  /*25h*/{ "ImpAdCallCy", 0, 5 },
  /*26h*/{ pcit_ive, 0, 1 },
  /*27h*/{ "ImpAdCallI4", 0, 5 },
  /*28h*/{ "ImpAdCallI4", 0, 5 },
  /*29h*/{ "ImpAdCallFPR4", 0, 5 },
  /*2Ah*/{ "ImpAdCallFPR4", 0, 5 },
  /*2Bh*/{ pcit_ive, 0, 1 },
  /*2Ch*/{ "ImpAdCallFPR4", 0, 5 },
  /*2Dh*/{ "ImpAdCallCbFrame", 0, 9 },
  /*2Eh*/{ "LdStkRf", 0, 3 },
  /*2Fh*/{ "LdFrameRf", 0, 3 },
  /*30h*/{ pcit_ive, 0, 1 },
  /*31h*/{ pcit_ive, 0, 1 },
  /*32h*/{ pcit_ive, 0, 1 },
  /*33h*/{ pcit_ive, 0, 1 },
  /*34h*/{ pcit_ive, 0, 1 },
  /*35h*/{ pcit_ive, 0, 1 },
  /*36h*/{ pcit_ive, 0, 1 },
  /*37h*/{ pcit_ive, 0, 1 },
  /*38h*/{ pcit_ive, 0, 1 },
  /*39h*/{ pcit_ive, 0, 1 },
  /*3Ah*/{ pcit_ive, 0, 1 },
  /*3Bh*/{ pcit_ive, 0, 1 },
  /*3Ch*/{ pcit_ive, 0, 1 },
  /*3Dh*/{ "LitVarUI1", 0, 5 },
  /*3Eh*/{ pcit_ive, 0, 1 },
  /*3Fh*/{ pcit_ive, 0, 1 },
  /*40h*/{ pcit_ive, 0, 1 },
  /*41h*/{ pcit_ive, 0, 1 },
  /*42h*/{ pcit_ive, 0, 1 },
  /*43h*/{ pcit_ive, 0, 1 },
  /*44h*/{ pcit_ive, 0, 1 },
  /*45h*/{ pcit_ive, 0, 1 },
  /*46h*/{ pcit_ive, 0, 1 },
  /*47h*/{ pcit_ive, 0, 1 },
  /*48h*/{ pcit_ive, 0, 1 },
  /*49h*/{ pcit_ive, 0, 1 },
  /*4Ah*/{ pcit_ive, 0, 1 },
  /*4Bh*/{ pcit_ive, 0, 1 },
  /*4Ch*/{ pcit_ive, 0, 1 },
  /*4Dh*/{ "SetVarVar", PCT_NONE, 1 },
  /*4Eh*/{ "SetVarVarFunc", PCT_NONE, 1 },
  /*4Fh*/{ "ImpAdCallHresult", 0, 5 },
  /*50h*/{ pcit_ive, 0, 1 },
  /*51h*/{ pcit_ive, 0, 1 },
  /*52h*/{ pcit_ive, 0, 1 },
  /*53h*/{ pcit_ive, 0, 1 },
  /*54h*/{ pcit_ive, 0, 1 },
  /*55h*/{ pcit_ive, 0, 1 },
  /*56h*/{ pcit_ive, 0, 1 },
  /*57h*/{ pcit_ive, 0, 1 },
  /*58h*/{ pcit_ive, 0, 1 },
  /*59h*/{ pcit_ive, 0, 1 },
  /*5Ah*/{ pcit_ive, 0, 1 },
  /*5Bh*/{ pcit_ive, 0, 1 },
  /*5Ch*/{ pcit_ive, 0, 1 },
  /*5Dh*/{ "OpenFile", 0, 3 },
  /*5Eh*/{ "LockFile", 0, 3 },
  /*5Fh*/{ pcit_ive, 0, 1 },
  /*60h*/{ "EraseDestruct", 0, 3 },
  /*61h*/{ "LdFixedStr", 0, 3 },
  /*62h*/{ "ForUI1", 0, 5 },
  /*63h*/{ "ForI2", 0, 5 },
  /*64h*/{ "ForI4", 0, 5 },
  /*65h*/{ "ForR4", 0, 5 },
  /*66h*/{ "ForR8", 0, 5 },
  /*67h*/{ "ForCy", 0, 5 },
  /*68h*/{ "ForVar", 0, 5 },
  /*69h*/{ pcit_ive, 0, 1 },
  /*6Ah*/{ "ForStepUI1", 0, 5 },
  /*6Bh*/{ "ForStepI2", 0, 5 },
  /*6Ch*/{ "ForStepI4", 0, 5 },
  /*6Dh*/{ "ForStepR4", 0, 5 },
  /*6Eh*/{ "ForStepR8", 0, 5 },
  /*6Fh*/{ "ForStepCy", 0, 5 },
  /*70h*/{ "ForStepVar", 0, 5 },
  /*71h*/{ pcit_ive, 0, 1 },
  /*72h*/{ "ForEachCollVar", 0, 5 },
  /*73h*/{ "NextEachCollVar", 0, 5 },
  /*74h*/{ "ForEachCollAd", 0, 5 },
  /*75h*/{ "NextEachCollAd", 0, 5 },
  /*76h*/{ "ForEachAryVar", 0, 7 },
  /*77h*/{ "NextEachAryVar", 0, 7 },
  /*78h*/{ "NextUI1", 0, 5 },
  /*79h*/{ "NextI2", 0, 5 },
  /*7Ah*/{ "NextI4", 0, 5 },
  /*7Bh*/{ "NextStepR4", 0, 5 },
  /*7Ch*/{ "NextR8", 0, 5 },
  /*7Dh*/{ "NextStepCy", 0, 5 },
  /*7Eh*/{ "NextStepVar", 0, 5 },
  /*7Fh*/{ pcit_ive, 0, 1 },
  /*80h*/{ "NextStepUI1", 0, 5 },
  /*81h*/{ "NextStepI2", 0, 5 },
  /*82h*/{ "NextStepI4", 0, 5 },
  /*83h*/{ "NextStepR4", 0, 5 },
  /*84h*/{ "NextR8", 0, 5 },
  /*85h*/{ "NextStepCy", 0, 5 },
  /*86h*/{ "NextStepVar", 0, 5 },
  /*87h*/{ pcit_ive, 0, 1 },
  /*88h*/{ "ForEachCollObj", 0, 7 },
  /*89h*/{ "ForEachVar", 0, 5 },
  /*8Ah*/{ "ForEachVarFree", 0, 5 },
  /*8Bh*/{ "NextEachCollObj", PCT_NONE, 7 },
  /*8Ch*/{ "NextEachVar", 0, 9 },
  /*8Dh*/{ "CheckType", 0, 3 },
  /*8Eh*/{ "Redim", 0, 9 },
  /*8Fh*/{ "RedimPreserve", 0, 9 },
  /*90h*/{ "RedimVar", 0, 5 },
  /*91h*/{ "RedimPreserveVar", 0, 5 },
  /*92h*/{ "FDupVar", 0, 5 },
  /*93h*/{ "FDupStr", 0, 5 },
  /*94h*/{ pcit_ive, 0, 1 },
  /*95h*/{ "OnGosub", 0, 7 },
  /*96h*/{ "OnGoto", 0, 7 },
  /*97h*/{ "AddRef", PCT_NONE, 1 },
  /*98h*/{ "LateMemCall", 0, 5 },
  /*99h*/{ "LateMemLdVar", 0, 5 },
  /*9Ah*/{ "LateMemCallLdVar", 0, 7 },
  /*9Bh*/{ "LateMemSt", 0, 3 },
  /*9Ch*/{ "LateMemCallSt", 0, 5 },
  /*9Dh*/{ "LateMemStAd", 0, 5 },
  /*9Eh*/{ "ExitProcFrameCb", 0, 4 },
  /*9Fh*/{ "ExitProcFrameCbStack", 0, 4 },
  /*A0h*/{ "LateIdCall", 0, 7 },
  /*A1h*/{ "LateIdLdVar", 0, 7 },
  /*A2h*/{ "LateIdCallLdVar", 0, 9 },
  /*A3h*/{ "LateIdSt", 0, 5 },
  /*A4h*/{ "LateIdCallSt", 0, 7 },
  /*A5h*/{ "LateIdStAd", 0, 7 },
  /*A6h*/{ "LateMemNamedCall", 0, 7 },
  /*A7h*/{ "LateMemNamedCallLdVar", 0, 9 },
  /*A8h*/{ "LateMemNamedCallSt", 0, 7 },
  /*A9h*/{ "LateMemNamedStAd", 0, 7 },
  /*AAh*/{ "LateIdNamedCall", 0, 9 },
  /*ABh*/{ "LateIdNamedCallLdVar", 0, 1 },
  /*ACh*/{ "LateIdNamedCallSt", 0, 9 },
  /*ADh*/{ "LateIdNamedStAd", 0, 9 },
  /*AEh*/{ "VarIndexLdVar", 0, 5 },
  /*AFh*/{ "VarIndexLdRfVar", 0, 5 },
  /*B0h*/{ "VarIndexSt", 0, 3 },
  /*B1h*/{ "VarIndexStAd", 0, 3 },
  /*B2h*/{ "FFreeVar", PCT_NONE, -1 },
  /*B3h*/{ "FFreeStr", PCT_NONE, -1 },
  /*B4h*/{ "FFreeAd", 0, -1 },
  /*B5h*/{ "LitI2", 0, 3 },
  /*B6h*/{ "LitI2FP", 0, 3 },
  /*B7h*/{ "LitCy4", 0, 5 },
  /*B8h*/{ "LitI4", 0, 5 },
  /*B9h*/{ "LitI4", 0, 5 },
  /*BAh*/{ "LitR4FP", 0, 5 },
  /*BBh*/{ "LitR8", 0, 9 },
  /*BCh*/{ "LitR8", 0, 9 },
  /*BDh*/{ "LitR8FP", 0, 9 },
  /*BEh*/{ "LitR8FP", 0, 9 },
  /*BFh*/{ "LitStr", 0, 3 },
  /*C0h*/{ "LitVarI2", 0, 5 },
  /*C1h*/{ "LitVarI4", 0, 7 },
  /*C2h*/{ "LitVarR4", 0, 7 },
  /*C3h*/{ "LitVarCy", 0, 1 },
  /*C4h*/{ "LitVarR8", 0, 11 },
  /*C5h*/{ "LitVarDate", 0, 1 },
  /*C6h*/{ "LitVarStr", 0, 5 },
  /*C7h*/{ "CStrBool", PCT_NONE, 1 },
  /*C8h*/{ "CStrDate", PCT_NONE, 1 },
  /*C9h*/{ "CDateStr", PCT_NONE, 1 },
  /*CAh*/{ pcit_ive, 0, 1 },
  /*CBh*/{ pcit_ive, 0, 1 },
  /*CCh*/{ "FreeStrNoPop", 0, 1 },
  /*CDh*/{ "FreeVarNoPop", 0, 1 },
  /*CEh*/{ "FreeAdNoPop", 0, 1 },
  /*CFh*/{ "EraseNoPop", PCT_NONE, 1 },
  /*D0h*/{ "WMemLdUI1", 0, 3 },
  /*D1h*/{ "WMemLdI2", 0, 3 },
  /*D2h*/{ "WMemLdStr", 0, 3 },
  /*D3h*/{ "WMemLdStr", 0, 3 },
  /*D4h*/{ "WMemLdCy", 0, 3 },
  /*D5h*/{ "WMemLdCy", 0, 3 },
  /*D6h*/{ "WMemLdRfVar", 0, 3 },
  /*D7h*/{ "WMemLdStr", 0, 3 },
  /*D8h*/{ "WMemLdStr", 0, 3 },
  /*D9h*/{ "WMemLdFPR4", 0, 3 },
  /*DAh*/{ "WMemLdFPR8", 0, 3 },
  /*DBh*/{ "IWMemLdPr", 0, 3 },
  /*DCh*/{ "WMemLdRfVar", 0, 3 },
  /*DDh*/{ "WMemLdVar", 0, 3 },
  /*DEh*/{ pcit_ive, 0, 1 },
  /*DFh*/{ pcit_ive, 0, 1 },
  /*E0h*/{ "WMemStUI1", 0, 3 },
  /*E1h*/{ "WMemStI2", 0, 3 },
  /*E2h*/{ "WMemStR4", 0, 3 },
  /*E3h*/{ "WMemStR4", 0, 3 },
  /*E4h*/{ "WMemStR8", 0, 3 },
  /*E5h*/{ "WMemStR8", 0, 3 },
  /*E6h*/{ "WMemStVar", 0, 3 },
  /*E7h*/{ "WMemStStr", 0, 3 },
  /*E8h*/{ "WMemStAd", 0, 3 },
  /*E9h*/{ "WMemStFPR4", 0, 3 },
  /*EAh*/{ "WMemStFPR8", 0, 3 },
  /*EBh*/{ "WMemStVarAd", 0, 3 },
  /*ECh*/{ "WMemStVarAdFunc", 0, 3 },
  /*EDh*/{ "WMemStVarUnk", 0, 3 },
  /*EEh*/{ "WMemStVarUnkFunc", 0, 3 },
  /*EFh*/{ "WMemStAdFunc", 0, 3 },
  /*F0h*/{ "WMemStVarCopy", 0, 3 },
  /*F1h*/{ "WMemStStrCopy", 0, 3 },
  /*F2h*/{ "VarIndexLdRfVarLock", 0, 7 },
  /*F3h*/{ "InvalidExcod", 0, 1 },
  /*F4h*/{ "InvalidExcod", 0, 1 },
  /*F5h*/{ "AssignRecord", 0, 3 },
  /*F6h*/{ "DestructAnsiOFrame", 0, 5 },
  /*F7h*/{ "FStVarZero", 0, 3 },
  /*F8h*/{ "FStVarCopyObj", 0, 3 },
  /*F9h*/{ "VerifyVarObj", 0, 1 },
  /*FAh*/{ "VerifyPVarObj", PCT_NONE, 1 },
  /*FBh*/{ "FnInStrB4", PCT_NONE, 1 },
  /*FCh*/{ "FnInStrB4Var", 0, 3 },
  /*FDh*/{ "FnInStr4", PCT_NONE, 1 },
  /*FEh*/{ "FnInStr4Var", 0, 3 },
  /*FFh*/{ "FnStrComp3", PCT_NONE, 1 }
};

/*P-Code 双字节指令集4 (扩展指令集) 0xFF前缀*/
const VB_PCODE_LEAD_INST PCodeLead4Inst[256] =
{
  /*00h*/{ "FnStrComp3Var", 0, 3 },
  /*01h*/{ "StAryMove", PCT_NONE, 1 },
  /*02h*/{ "StAryCopy", PCT_NONE, 1 },
  /*03h*/{ "StAryRecMove", 0, 3 },
  /*04h*/{ "StAryRecCopy", 0, 3 },
  /*05h*/{ pcit_ive, 0, 1 },
  /*06h*/{ "AryInRecLdPr", 0, 5 },
  /*07h*/{ "AryInRecLdRf", 0, 5 },
  /*08h*/{ "CExtInstUnk", 0, 1 },
  /*09h*/{ "IStVarCopyObj", 0, 3 },
  /*0Ah*/{ "ArrayRebase1Var", PCT_NONE, 1 },
  /*0Bh*/{ "Assert", PCT_NONE, 1 },
  /*0Ch*/{ "RaiseEvent", 0, 7 },
  /*0Dh*/{ "PrintObject", 0, 5 },
  /*0Eh*/{ "PrintFile", 0, 5 },
  /*0Fh*/{ "WriteFile", 0, 5 },
  /*10h*/{ "InputFile", 0, 5 },
  /*11h*/{ pcit_ive, 0, 1 },
  /*12h*/{ "GetRecFxStr3", PCT_NONE, 1 },
  /*13h*/{ "GetRecFxStr4", PCT_NONE, 1 },
  /*14h*/{ "PutRecFxStr3", 0, 1 },
  /*15h*/{ "PutRecFxStr4", 0, 1 },
  /*16h*/{ "GetRecOwn3", 0, 3 },
  /*17h*/{ "GetRecOwn4", 0, 3 },
  /*18h*/{ "PutRecOwn3", 0, 3 },
  /*19h*/{ "PutRecOwn4", 0, 3 },
  /*1Ah*/{ "LitI2_Byte", 0, 2 },
  /*1Bh*/{ "CBoolVarNull", PCT_NONE, 1 },
  /*1Ch*/{ "LargeBos", 0, 2 },
  /*1Dh*/{ "Bos", 0, 1 },
  /*1Eh*/{ "ImpAdCallNonVirt", 0, 5 },
  /*1Fh*/{ pcit_ive, 0, 1 },
  /*20h*/{ pcit_ive, 0, 1 },
  /*21h*/{ pcit_ive, 0, 1 },
  /*22h*/{ pcit_ive, 0, 1 },
  /*23h*/{ pcit_ive, 0, 1 },
  /*24h*/{ pcit_ive, 0, 1 },
  /*25h*/{ pcit_ive, 0, 1 },
  /*26h*/{ pcit_ive, 0, 1 },
  /*27h*/{ pcit_ive, 0, 1 },
  /*28h*/{ pcit_ive, 0, 1 },
  /*29h*/{ pcit_ive, 0, 1 },
  /*2Ah*/{ "DestructRecord", 0, 3 },
  /*2Bh*/{ "VCallFPR8", 0, 3 },
  /*2Ch*/{ "ThisVCallHidden", 0, 3 },
  /*2Dh*/{ "ZeroRetVal", PCT_NONE, 1 },
  /*2Eh*/{ "ZeroRetValVar", PCT_NONE, 1 },
  /*2Fh*/{ "ExitProcCbHresult", PCF_ENDPROC, 5 },
  /*30h*/{ "ExitProcFrameCbHresult", 0, 7 },
  /*31h*/{ "EraseDestrKeepData", 0, 3 },
  /*32h*/{ "CDargRefUdt", 0, 5 },
  /*33h*/{ "CVarRefUdt", 0, 5 },
  /*34h*/{ "CVarUdt", 0, 5 },
  /*35h*/{ "StUdtVar", 0, 3 },
  /*36h*/{ "StAryVar", 0, 3 },
  /*37h*/{ "CopyBytesZero", 0, 3 },
  /*38h*/{ "FLdZeroAry", 0, 5 },
  /*39h*/{ "FStVarZero", 0, 3 },
  /*3Ah*/{ "CVarAryUdt", 0, 7 },
  /*3Bh*/{ "RedimVarUdt", 0, 7 },
  /*3Ch*/{ "RedimPreserveVarUdt", 0, 7 },
  /*3Dh*/{ "VarLateMemLdRfVar", 0, 5 },
  /*3Eh*/{ "VarLateMemCallLdRfVar", 0, 6 },
  /*3Fh*/{ pcit_ive, 0, 1 },
  /*40h*/{ pcit_ive, 0, 1 },
  /*41h*/{ "VarLateMemLdVar", 0, 5 },
  /*42h*/{ "VarLateMemCallLdVar", 0, 7 },
  /*43h*/{ "VarLateMemSt", 0, 3 },
  /*44h*/{ "VarLateMemCallSt", 0, 5 },
  /*45h*/{ "VarLateMemStAd", 0, 5 },
  /*46h*/{ pcit_ive, 0, 1 },
  /*47h*/{ pcit_unk, 0, 1 },
  /*48h*/{ pcit_unk, 0, 1 },
  /*49h*/{ pcit_unk, 0, 1 },
  /*4Ah*/{ pcit_unk, 0, 1 },
  /*4Bh*/{ pcit_unk, 0, 1 },
  /*4Ch*/{ pcit_unk, 0, 1 },
  /*4Dh*/{ pcit_unk, 0, 1 },
  /*4Eh*/{ pcit_unk, 0, 1 },
  /*4Fh*/{ pcit_unk, 0, 1 },
  /*50h*/{ pcit_unk, 0, 1 },
  /*51h*/{ pcit_unk, 0, 1 },
  /*52h*/{ pcit_unk, 0, 1 },
  /*53h*/{ pcit_unk, 0, 1 },
  /*54h*/{ pcit_unk, 0, 1 },
  /*55h*/{ pcit_unk, 0, 1 },
  /*56h*/{ pcit_unk, 0, 1 },
  /*57h*/{ pcit_unk, 0, 1 },
  /*58h*/{ pcit_unk, 0, 1 },
  /*59h*/{ pcit_unk, 0, 1 },
  /*5Ah*/{ pcit_unk, 0, 1 },
  /*5Bh*/{ pcit_unk, 0, 1 },
  /*5Ch*/{ pcit_unk, 0, 1 },
  /*5Dh*/{ pcit_unk, 0, 1 },
  /*5Eh*/{ pcit_unk, 0, 1 },
  /*5Fh*/{ pcit_unk, 0, 1 },
  /*60h*/{ pcit_unk, 0, 1 },
  /*61h*/{ pcit_unk, 0, 1 },
  /*62h*/{ pcit_unk, 0, 1 },
  /*63h*/{ pcit_unk, 0, 1 },
  /*64h*/{ pcit_unk, 0, 1 },
  /*65h*/{ pcit_unk, 0, 1 },
  /*66h*/{ pcit_unk, 0, 1 },
  /*67h*/{ pcit_unk, 0, 1 },
  /*68h*/{ pcit_unk, 0, 1 },
  /*69h*/{ pcit_unk, 0, 1 },
  /*6Ah*/{ pcit_unk, 0, 1 },
  /*6Bh*/{ pcit_unk, 0, 1 },
  /*6Ch*/{ pcit_unk, 0, 1 },
  /*6Dh*/{ pcit_unk, 0, 1 },
  /*6Eh*/{ pcit_unk, 0, 1 },
  /*6Fh*/{ pcit_unk, 0, 1 },
  /*70h*/{ pcit_unk, 0, 1 },
  /*71h*/{ pcit_unk, 0, 1 },
  /*72h*/{ pcit_unk, 0, 1 },
  /*73h*/{ pcit_unk, 0, 1 },
  /*74h*/{ pcit_unk, 0, 1 },
  /*75h*/{ pcit_unk, 0, 1 },
  /*76h*/{ pcit_unk, 0, 1 },
  /*77h*/{ pcit_unk, 0, 1 },
  /*78h*/{ pcit_unk, 0, 1 },
  /*79h*/{ pcit_unk, 0, 1 },
  /*7Ah*/{ pcit_unk, 0, 1 },
  /*7Bh*/{ pcit_unk, 0, 1 },
  /*7Ch*/{ pcit_unk, 0, 1 },
  /*7Dh*/{ pcit_unk, 0, 1 },
  /*7Eh*/{ pcit_unk, 0, 1 },
  /*7Fh*/{ pcit_unk, 0, 1 },
  /*80h*/{ pcit_unk, 0, 1 },
  /*81h*/{ pcit_unk, 0, 1 },
  /*82h*/{ pcit_unk, 0, 1 },
  /*83h*/{ pcit_unk, 0, 1 },
  /*84h*/{ pcit_unk, 0, 1 },
  /*85h*/{ pcit_unk, 0, 1 },
  /*86h*/{ pcit_unk, 0, 1 },
  /*87h*/{ pcit_unk, 0, 1 },
  /*88h*/{ pcit_unk, 0, 1 },
  /*89h*/{ pcit_unk, 0, 1 },
  /*8Ah*/{ pcit_unk, 0, 1 },
  /*8Bh*/{ pcit_unk, 0, 1 },
  /*8Ch*/{ pcit_unk, 0, 1 },
  /*8Dh*/{ pcit_unk, 0, 1 },
  /*8Eh*/{ pcit_unk, 0, 1 },
  /*8Fh*/{ pcit_unk, 0, 1 },
  /*90h*/{ pcit_unk, 0, 1 },
  /*91h*/{ pcit_unk, 0, 1 },
  /*92h*/{ pcit_unk, 0, 1 },
  /*93h*/{ pcit_unk, 0, 1 },
  /*94h*/{ pcit_unk, 0, 1 },
  /*95h*/{ pcit_unk, 0, 1 },
  /*96h*/{ pcit_unk, 0, 1 },
  /*97h*/{ pcit_unk, 0, 1 },
  /*98h*/{ pcit_unk, 0, 1 },
  /*99h*/{ pcit_unk, 0, 1 },
  /*9Ah*/{ pcit_unk, 0, 1 },
  /*9Bh*/{ pcit_unk, 0, 1 },
  /*9Ch*/{ pcit_unk, 0, 1 },
  /*9Dh*/{ pcit_unk, 0, 1 },
  /*9Eh*/{ pcit_unk, 0, 1 },
  /*9Fh*/{ pcit_unk, 0, 1 },
  /*A0h*/{ pcit_unk, 0, 1 },
  /*A1h*/{ pcit_unk, 0, 1 },
  /*A2h*/{ pcit_unk, 0, 1 },
  /*A3h*/{ pcit_unk, 0, 1 },
  /*A4h*/{ pcit_unk, 0, 1 },
  /*A5h*/{ pcit_unk, 0, 1 },
  /*A6h*/{ pcit_unk, 0, 1 },
  /*A7h*/{ pcit_unk, 0, 1 },
  /*A8h*/{ pcit_unk, 0, 1 },
  /*A9h*/{ pcit_unk, 0, 1 },
  /*AAh*/{ pcit_unk, 0, 1 },
  /*ABh*/{ pcit_unk, 0, 1 },
  /*ACh*/{ pcit_unk, 0, 1 },
  /*ADh*/{ pcit_unk, 0, 1 },
  /*AEh*/{ pcit_unk, 0, 1 },
  /*AFh*/{ pcit_unk, 0, 1 },
  /*B0h*/{ pcit_unk, 0, 1 },
  /*B1h*/{ pcit_unk, 0, 1 },
  /*B2h*/{ pcit_unk, 0, 1 },
  /*B3h*/{ pcit_unk, 0, 1 },
  /*B4h*/{ pcit_unk, 0, 1 },
  /*B5h*/{ pcit_unk, 0, 1 },
  /*B6h*/{ pcit_unk, 0, 1 },
  /*B7h*/{ pcit_unk, 0, 1 },
  /*B8h*/{ pcit_unk, 0, 1 },
  /*B9h*/{ pcit_unk, 0, 1 },
  /*BAh*/{ pcit_unk, 0, 1 },
  /*BBh*/{ pcit_unk, 0, 1 },
  /*BCh*/{ pcit_unk, 0, 1 },
  /*BDh*/{ pcit_unk, 0, 1 },
  /*BEh*/{ pcit_unk, 0, 1 },
  /*BFh*/{ pcit_unk, 0, 1 },
  /*C0h*/{ pcit_unk, 0, 1 },
  /*C1h*/{ pcit_unk, 0, 1 },
  /*C2h*/{ pcit_unk, 0, 1 },
  /*C3h*/{ pcit_unk, 0, 1 },
  /*C4h*/{ pcit_unk, 0, 1 },
  /*C5h*/{ pcit_unk, 0, 1 },
  /*C6h*/{ pcit_unk, 0, 1 },
  /*C7h*/{ pcit_unk, 0, 1 },
  /*C8h*/{ pcit_unk, 0, 1 },
  /*C9h*/{ pcit_unk, 0, 1 },
  /*CAh*/{ pcit_unk, 0, 1 },
  /*CBh*/{ pcit_unk, 0, 1 },
  /*CCh*/{ pcit_unk, 0, 1 },
  /*CDh*/{ pcit_unk, 0, 1 },
  /*CEh*/{ pcit_unk, 0, 1 },
  /*CFh*/{ pcit_unk, 0, 1 },
  /*D0h*/{ pcit_unk, 0, 1 },
  /*D1h*/{ pcit_unk, 0, 1 },
  /*D2h*/{ pcit_unk, 0, 1 },
  /*D3h*/{ pcit_unk, 0, 1 },
  /*D4h*/{ pcit_unk, 0, 1 },
  /*D5h*/{ pcit_unk, 0, 1 },
  /*D6h*/{ pcit_unk, 0, 1 },
  /*D7h*/{ pcit_unk, 0, 1 },
  /*D8h*/{ pcit_unk, 0, 1 },
  /*D9h*/{ pcit_unk, 0, 1 },
  /*DAh*/{ pcit_unk, 0, 1 },
  /*DBh*/{ pcit_unk, 0, 1 },
  /*DCh*/{ pcit_unk, 0, 1 },
  /*DDh*/{ pcit_unk, 0, 1 },
  /*DEh*/{ pcit_unk, 0, 1 },
  /*DFh*/{ pcit_unk, 0, 1 },
  /*E0h*/{ pcit_unk, 0, 1 },
  /*E1h*/{ pcit_unk, 0, 1 },
  /*E2h*/{ pcit_unk, 0, 1 },
  /*E3h*/{ pcit_unk, 0, 1 },
  /*E4h*/{ pcit_unk, 0, 1 },
  /*E5h*/{ pcit_unk, 0, 1 },
  /*E6h*/{ pcit_unk, 0, 1 },
  /*E7h*/{ pcit_unk, 0, 1 },
  /*E8h*/{ pcit_unk, 0, 1 },
  /*E9h*/{ pcit_unk, 0, 1 },
  /*EAh*/{ pcit_unk, 0, 1 },
  /*EBh*/{ pcit_unk, 0, 1 },
  /*ECh*/{ pcit_unk, 0, 1 },
  /*EDh*/{ pcit_unk, 0, 1 },
  /*EEh*/{ pcit_unk, 0, 1 },
  /*EFh*/{ pcit_unk, 0, 1 },
  /*F0h*/{ pcit_unk, 0, 1 },
  /*F1h*/{ pcit_unk, 0, 1 },
  /*F2h*/{ pcit_unk, 0, 1 },
  /*F3h*/{ pcit_unk, 0, 1 },
  /*F4h*/{ pcit_unk, 0, 1 },
  /*F5h*/{ pcit_unk, 0, 1 },
  /*F6h*/{ pcit_unk, 0, 1 },
  /*F7h*/{ pcit_unk, 0, 1 },
  /*F8h*/{ pcit_unk, 0, 1 },
  /*F9h*/{ pcit_unk, 0, 1 },
  /*FAh*/{ pcit_unk, 0, 1 },
  /*FBh*/{ pcit_unk, 0, 1 },
  /*FCh*/{ pcit_unk, 0, 1 },
  /*FDh*/{ pcit_unk, 0, 1 },
  /*FEh*/{ pcit_unk, 0, 1 },
  /*FFh*/{ pcit_unk, 0, 1 }
};

const VB_PCODE_LEAD_INST * pvbinst[5] =
{
  PCodeLead0Inst,
  PCodeLead1Inst,
  PCodeLead2Inst,
  PCodeLead3Inst,
  PCodeLead4Inst
};

#pragma const_seg()
#pragma data_seg()